describe('Origin: /accommodation', () => {
  it('test', () => {
    cy.createAssessment()
    cy.visitStep('/accommodation')
    cy.getQuestion('What type of accommodation does Sam currently have?').getRadio('Settled').clickLabel()
    cy.getQuestion('What type of accommodation does Sam currently have?')
      .getRadio('Settled')
      .getConditionalQuestion()
      .getRadio('Homeowner')
      .clickLabel()
    cy.saveAndContinue()
    cy.assertStepUrlIs('/settled-accommodation')

    cy.createAssessment()
    cy.visitStep('/accommodation')
    cy.getQuestion('What type of accommodation does Sam currently have?').getRadio('Temporary').clickLabel()
    cy.getQuestion('What type of accommodation does Sam currently have?')
      .getRadio('Temporary')
      .getConditionalQuestion()
      .getRadio('Immigration accommodation')
      .clickLabel()
    cy.saveAndContinue()
    cy.assertStepUrlIs('/temporary-accommodation')
  })
})
