services:
  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - "5432:5432"

  hmpps-auth:
    ports:
      - "9090:9090"

  arns-handover:
    ports:
      - "7070:7070"

  oasys-ui:
    ports:
      - "7072:3000"

  hmpps-auth-proxy:
    image: nginx:latest
    depends_on:
      - hmpps-auth
      - arns-handover
    networks:
      - hmpps
    ports:
      - "9091:9091"
      - "7071:7071"
    volumes:
      - ./hmpps-auth-proxy/nginx.conf:/etc/nginx/nginx.conf

  api:
    ports:
      - "8080:8080"

  ui:
    image: quay.io/hmpps/hmpps-strengths-based-needs-assessments-ui:local
    build:
      target: development
    command: npm run start:dev
    depends_on:
      - hmpps-auth-proxy
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/app/app
      - ./assets:/app/assets
      - ./cypress:/app/cypress
      - ./esbuild:/app/esbuild
      - ./server:/app/server
      - ./test_results:/app/test_results
      - ./.eslintcache:/app/.eslintcache
      - ./.prettierrc:/app/.prettierrc
      - ./cypress.config.ts:/app/cypress.config.ts
      - ./eslint.config.mjs:/app/eslint.config.mjs
      - ./logger.ts:/app/logger.ts
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./server.ts:/app/server.ts
      - ./tsconfig.json:/app/tsconfig.json
