services:
  api:
    environment:
      LINK_BASE_URL: http://ui:3000/form

  ui:
    environment:
      INGRESS_URL: http://ui:3000
      HMPPS_AUTH_EXTERNAL_URL: http://hmpps-auth:9090/auth
      HMPPS_ARNS_HANDOVER_EXTERNAL_URL: http://arns-handover:7070

  arns-handover:
    environment:
      HMPPS_HANDOVER_EXTERNAL_URL: http://arns-handover:7070

  cypress:
    image: cypress/included
    networks:
      - hmpps
    volumes:
      - ./:/e2e
    working_dir: /e2e
    environment:
      CYPRESS_BASE_URL: http://ui:3000
      CYPRESS_SBNA_API_URL: http://api:8080
      CYPRESS_ARNS_HANDOVER_URL: http://arns-handover:7070
      CYPRESS_ARNS_HANDOVER_CLIENT_ID: strengths-and-needs-assessment
      CYPRESS_HMPPS_AUTH_URL: http://hmpps-auth:9090

volumes:
  test_results:
