#file: noinspection YAMLSchemaValidation
version: '3.8'
services:
  api:
    environment:
      LINK_BASE_URL: http://ui:3000/form

  ui:
    image: quay.io/hmpps/hmpps-strengths-based-needs-assessments-ui:${APP_VERSION:-latest}
    environment:
      INGRESS_URL: http://ui:3000
      HMPPS_AUTH_EXTERNAL_URL: http://hmpps-auth:9090/auth

  cypress:
    image: quay.io/hmpps/hmpps-strengths-based-needs-assessments-cypress:latest
    build:
      context: .
      dockerfile: ./cypress/Dockerfile
    networks:
      - hmpps
    environment:
      CYPRESS_BASE_URL: http://ui:3000
      CYPRESS_SBNA_API_URL: http://api:8080
      CYPRESS_HMPPS_AUTH_URL: http://hmpps-auth:9090
      SPLIT: ${CIRCLE_NODE_TOTAL:-1}
      SPLIT_INDEX: ${CIRCLE_NODE_INDEX:-0}
    volumes:
      - ./cypress:/e2e/cypress
      - ./test_results:/e2e/test_results

volumes:
  test_results:
