services:
  postgres:
    ports:
      - "5432:5432"

  coordinator-api:
    ports:
      - "8070:8080"

  san-api:
    ports:
      - "8080:8080"

  aap-ui:
    ports:
      - "7072:3000"

  san-ui:
    depends_on:
      - forward-proxy
    environment:
      FEEDBACK_URL: http://localhost:9092
    ports:
      - "3000:3000"

  arns-handover:
    volumes:
      - ./docker/handover/application-local.yml:/app/resources/application-local.yml
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/resources/application-local.yml
    ports:
      - "7070:7070"

  hmpps-auth:
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/9090'"]
      interval: 5s
      retries: 60
    ports:
      - "9090:9090"

  forward-proxy:
    image: nginx:latest
    depends_on:
      - hmpps-auth
      - arns-handover
    networks:
      - hmpps
    ports:
      - "9091:9091"
      - "9092:9092"
      - "7071:7071"
    volumes:
      - ./forward-proxy/nginx.conf:/etc/nginx/nginx.conf
