services:
  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - "5432:5432"

  hmpps-auth:
    ports:
      - "9090:9090"

  arns-handover:
    ports:
      - "7070:7070"

  oasys-ui:
    ports:
      - "7072:3000"

  hmpps-auth-proxy:
    image: nginx:latest
    depends_on:
      - hmpps-auth
      - arns-handover
    networks:
      - hmpps
    ports:
      - "9091:9091"
      - "7071:7071"
    volumes:
      - ./hmpps-auth-proxy/nginx.conf:/etc/nginx/nginx.conf

  api:
    ports:
      - "8080:8080"

  ui:
    image: quay.io/hmpps/hmpps-strengths-based-needs-assessments-ui:local
    build:
      target: development
    command: npm run start:dev
    depends_on:
      - hmpps-auth-proxy
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - code:/app
      - node_modules_volume:/app/node_modules
    tmpfs:
      - /app/dist

volumes:
  code:
  node_modules_volume:

x-mutagen:
  sync:
    defaults:
      mode: 'two-way-resolved'
      ignore:
        vcs: true
        paths:
          - '.idea'
          - 'node_modules'
          - 'dist'
    code:
      alpha: '.'
      beta: 'volume://code'