version: '3.1'
services:

  redis:
    image: redis:7.2
    networks:
      - hmpps
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    networks:
      - hmpps
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=9090
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  hmpps-strengths-based-needs-assessments-api:
    image: quay.io/hmpps/hmpps-strengths-based-needs-assessments-api:latest
    networks:
      - hmpps
    container_name: hmpps-strengths-based-needs-assessments-api
    depends_on:
     - postgres
    ports: 
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=postgres
      - OAUTH_ENDPOINT_URL=http://hmpps-auth:9090/auth
      - DATABASE_ENDPOINT=postgres:5432
      - APP_LINK_BASEURL=http://localhost:3000/form

  app:
    build: .
    networks:
      - hmpps
    depends_on: 
     - redis
     - hmpps-auth
     - hmpps-strengths-based-needs-assessments-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:9090/auth
      - TOKEN_VERIFICATION_ENABLED=false
      - NODE_ENV=development
      - API_CLIENT_SECRET=clientsecret
      - SYSTEM_CLIENT_SECRET=clientsecret
      - API_CLIENT_ID=hmpps-strengths-and-needs-ui
      - SYSTEM_CLIENT_ID=hmpps-strengths-and-needs-ui-client
      - SBNA_API_URL=http://hmpps-strengths-based-needs-assessments-api:8080

networks:
  hmpps:
