services:
  san-ui:
    environment:
      INGRESS_URL: http://san-ui:3000
      HMPPS_AUTH_EXTERNAL_URL: http://hmpps-auth:9090/auth
      HMPPS_ARNS_HANDOVER_EXTERNAL_URL: http://arns-handover:7070
      OASYS_URL: http://oasys-ui:3000
      KEEP_ALIVE: 30000      

  arns-handover:
    environment:
      HMPPS_HANDOVER_EXTERNAL_URL: http://arns-handover:7070
      CLIENT_SAN_OAUTH_REDIRECT_URI: http://san-ui:3000/sign-in/callback
      CLIENT_SAN_HANDOVER_REDIRECT_URI: http://san-ui:3000/sign-in
      OASYS_BASE_URL: http://oasys-ui:3000
      OASYS_RETURN_URLS: http://oasys-ui:3000

  oasys-ui:
    environment:
      INGRESS_URL: http://oasys-ui:3000

  cypress:
    image: cypress/included
    networks:
      - hmpps
    volumes:
      - ./:/e2e
    working_dir: /e2e
    environment:
      CYPRESS_BASE_URL: http://san-ui:3000
      CYPRESS_SBNA_API_URL: http://san-api:8080
      CYPRESS_COORDINATOR_API_URL: http://coordinator-api:8080
      CYPRESS_ARNS_HANDOVER_URL: http://arns-handover:7070
      CYPRESS_ARNS_HANDOVER_CLIENT_ID: strengths-and-needs-assessment
      CYPRESS_HMPPS_AUTH_URL: http://hmpps-auth:9090
      CYPRESS_OASYS_UI_URL: http://oasys-ui:3000

volumes:
  test_results:
