import FormWizard from 'hmpo-form-wizard'
import SaveAndContinueController from '../controllers/saveAndContinueController'

const stepOptions: FormWizard.Steps = {
  '/accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'current_accommodation',
      'type_of_settled_accommodation',
      'type_of_temporary_accommodation',
      'short_term_accommodation_end_date',
      'approved_premises_end_date',
      'cas2_end_date',
      'cas3_end_date',
      'immigration_accommodation_end_date',
      'type_of_no_accommodation',
      'awaiting_assessment_details',
      'accommodation_section_complete',
      'accommodation_analysis_section_complete',
    ],
    next: [
      { field: 'current_accommodation', value: 'SETTLED', next: 'settled-accommodation' },
      { field: 'type_of_temporary_accommodation', value: 'SHORT_TERM', next: 'temporary-accommodation-2' },
      { field: 'type_of_temporary_accommodation', value: 'IMMIGRATION', next: 'temporary-accommodation-2' },
      { field: 'current_accommodation', value: 'TEMPORARY', next: 'temporary-accommodation' },
      { field: 'type_of_no_accommodation', value: 'AWAITING_ASSESSMENT', next: 'no-accommodation-2' },
      { field: 'current_accommodation', value: 'NO_ACCOMMODATION', next: 'no-accommodation' },
    ],
    template: 'forms/default',
    navigationOrder: 1,
    section: 'accommodation',
    sectionProgressRules: [
      { fieldCode: 'accommodation_section_complete', conditionFn: () => 'NO' },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/settled-accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'living_with',
      'living_with_children_details',
      'living_with_partner_details',
      'living_with_other',
      'suitable_housing_location',
      'suitable_housing_location_concerns',
      'suitable_housing_location_concerns_other_details',
      'suitable_housing',
      'suitable_housing_concerns',
      'unsuitable_housing_concerns',
      'suitable_housing_concerns_other_details',
      'accommodation_changes',
      'accommodation_made_changes_details',
      'accommodation_making_changes_details',
      'accommodation_want_to_make_changes_details',
      'accommodation_needs_help_to_make_changes_details',
      'accommodation_thinking_about_making_changes_details',
      'accommodation_does_not_want_to_make_changes_details',
      'accommodation_section_complete',
      'accommodation_analysis_section_complete',
    ],
    next: 'accommodation-summary-analysis-settled',
    template: 'forms/default',
    backLink: 'accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      { fieldCode: 'accommodation_section_complete', conditionFn: (isValid: boolean) => (isValid ? 'YES' : 'NO') },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/temporary-accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'living_with',
      'living_with_children_details',
      'living_with_partner_details',
      'living_with_other',
      'suitable_housing_location',
      'suitable_housing_location_concerns',
      'suitable_housing_location_concerns_other_details',
      'suitable_housing',
      'suitable_housing_concerns',
      'unsuitable_housing_concerns',
      'suitable_housing_concerns_other_details',
      'suitable_housing_planned',
      'future_accommodation_type',
      'suitable_housing_planned_awaiting_assessment_details',
      'awaiting_accommodation_placement_details',
      'suitable_housing_planned_other_details',
      'accommodation_changes',
      'accommodation_made_changes_details',
      'accommodation_making_changes_details',
      'accommodation_want_to_make_changes_details',
      'accommodation_needs_help_to_make_changes_details',
      'accommodation_thinking_about_making_changes_details',
      'accommodation_does_not_want_to_make_changes_details',
      'accommodation_section_complete',
      'accommodation_analysis_section_complete',
    ],
    next: 'accommodation-summary-analysis-temporary',
    template: 'forms/default',
    backLink: 'accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      { fieldCode: 'accommodation_section_complete', conditionFn: (isValid: boolean) => (isValid ? 'YES' : 'NO') },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/temporary-accommodation-2': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'suitable_housing_location',
      'suitable_housing_location_concerns',
      'suitable_housing_location_concerns_other_details',
      'suitable_housing',
      'suitable_housing_concerns',
      'unsuitable_housing_concerns',
      'suitable_housing_concerns_other_details',
      'suitable_housing_planned',
      'future_accommodation_type',
      'suitable_housing_planned_awaiting_assessment_details',
      'awaiting_accommodation_placement_details',
      'suitable_housing_planned_other_details',
      'accommodation_changes',
      'accommodation_made_changes_details',
      'accommodation_making_changes_details',
      'accommodation_want_to_make_changes_details',
      'accommodation_needs_help_to_make_changes_details',
      'accommodation_thinking_about_making_changes_details',
      'accommodation_does_not_want_to_make_changes_details',
      'accommodation_section_complete',
      'accommodation_analysis_section_complete',
    ],
    next: 'accommodation-summary-analysis-temporary',
    template: 'forms/default',
    backLink: 'accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/no-accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'no_accommodation_reason',
      'no_accommodation_reason_other_details',
      'past_accommodation_details',
      'suitable_housing_planned',
      'future_accommodation_type',
      'suitable_housing_planned_awaiting_assessment_details',
      'awaiting_accommodation_placement_details',
      'suitable_housing_planned_other_details',
      'accommodation_changes',
      'accommodation_made_changes_details',
      'accommodation_making_changes_details',
      'accommodation_want_to_make_changes_details',
      'accommodation_needs_help_to_make_changes_details',
      'accommodation_thinking_about_making_changes_details',
      'accommodation_does_not_want_to_make_changes_details',
      'accommodation_section_complete',
      'accommodation_analysis_section_complete',
    ],
    next: 'accommodation-summary-analysis-no-accommodation',
    template: 'forms/default',
    backLink: 'accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/no-accommodation-2': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'accommodation_changes',
      'accommodation_made_changes_details',
      'accommodation_making_changes_details',
      'accommodation_want_to_make_changes_details',
      'accommodation_needs_help_to_make_changes_details',
      'accommodation_thinking_about_making_changes_details',
      'accommodation_does_not_want_to_make_changes_details',
      'accommodation_section_complete',
      'accommodation_analysis_section_complete',
    ],
    next: 'accommodation-summary-analysis-no-accommodation',
    template: 'forms/default',
    backLink: 'accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/accommodation-summary-analysis-no-accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'accommodation_practitioner_analysis_patterns_of_behaviour',
      'accommodation_practitioner_analysis_patterns_of_behaviour_details',
      'accommodation_practitioner_analysis_strengths_or_protective_factors',
      'accommodation_practitioner_analysis_strengths_or_protective_factors_details',
      'accommodation_practitioner_analysis_risk_of_serious_harm',
      'accommodation_practitioner_analysis_risk_of_serious_harm_details',
      'accommodation_practitioner_analysis_risk_of_reoffending',
      'accommodation_practitioner_analysis_risk_of_reoffending_details',
      'accommodation_practitioner_analysis_related_to_risk',
      'accommodation_practitioner_analysis_related_to_risk_details',
      'accommodation_analysis_section_complete',
    ],
    next: 'accommodation-analysis-complete-no-accommodation#practitioner-analysis',
    template: 'forms/sbna-poc/accommodation-summary-analysis-no-accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_analysis_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
    ],
  },
  '/accommodation-summary-analysis-temporary': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'accommodation_practitioner_analysis_patterns_of_behaviour',
      'accommodation_practitioner_analysis_patterns_of_behaviour_details',
      'accommodation_practitioner_analysis_strengths_or_protective_factors',
      'accommodation_practitioner_analysis_strengths_or_protective_factors_details',
      'accommodation_practitioner_analysis_risk_of_serious_harm',
      'accommodation_practitioner_analysis_risk_of_serious_harm_details',
      'accommodation_practitioner_analysis_risk_of_reoffending',
      'accommodation_practitioner_analysis_risk_of_reoffending_details',
      'accommodation_practitioner_analysis_related_to_risk',
      'accommodation_practitioner_analysis_related_to_risk_details',
      'accommodation_analysis_section_complete',
    ],
    next: 'accommodation-analysis-complete-temporary#practitioner-analysis',
    template: 'forms/sbna-poc/accommodation-summary-analysis-temporary',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_analysis_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
    ],
  },
  '/accommodation-summary-analysis-settled': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'accommodation_practitioner_analysis_patterns_of_behaviour',
      'accommodation_practitioner_analysis_patterns_of_behaviour_details',
      'accommodation_practitioner_analysis_strengths_or_protective_factors',
      'accommodation_practitioner_analysis_strengths_or_protective_factors_details',
      'accommodation_practitioner_analysis_risk_of_serious_harm',
      'accommodation_practitioner_analysis_risk_of_serious_harm_details',
      'accommodation_practitioner_analysis_risk_of_reoffending',
      'accommodation_practitioner_analysis_risk_of_reoffending_details',
      'accommodation_practitioner_analysis_related_to_risk',
      'accommodation_practitioner_analysis_related_to_risk_details',
      'accommodation_analysis_section_complete',
    ],
    next: 'accommodation-analysis-complete-settled#practitioner-analysis',
    template: 'forms/sbna-poc/accommodation-summary-analysis-settled',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_analysis_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
    ],
  },
  '/accommodation-analysis-complete-settled': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    next: 'employment-education-finance',
    template: 'forms/sbna-poc/accommodation-analysis-complete-settled',
    section: 'accommodation',
  },
  '/accommodation-analysis-complete-temporary': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    next: 'employment-education-finance',
    template: 'forms/sbna-poc/accommodation-analysis-complete-temporary',
    section: 'accommodation',
  },
  '/accommodation-analysis-complete-no-accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    next: 'employment-education-finance',
    template: 'forms/sbna-poc/accommodation-analysis-complete-no-accommodation',
    section: 'accommodation',
  },
}

export default stepOptions
