import FormWizard from 'hmpo-form-wizard'
import SaveAndContinueController from '../controllers/saveAndContinueController'

const stepOptions: FormWizard.Steps = {
  '/drug-use': {
    pageTitle: 'Drug use',
    controller: SaveAndContinueController,
    fields: ['drug_use', 'drug_use_section_complete', 'drug_use_analysis_section_complete'],
    next: [
      { field: 'drug_use', value: 'YES', next: 'drug-use-details' },
      { field: 'drug_use', value: 'NO', next: 'drug-use-analysis' },
    ],
    template: 'forms/default',
    navigationOrder: 4,
    section: 'drug-use',
    sectionProgressRules: [
      {
        fieldCode: 'drug_use_section_complete',
        conditionFn: (isValid: boolean, answers: Record<string, string | string[]>) =>
          isValid && answers.drug_use === 'NO' ? 'YES' : 'NO',
      },
      { fieldCode: 'drug_use_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/drug-use-details': {
    pageTitle: 'Drug use',
    controller: SaveAndContinueController,
    fields: [
      'drug_use_reasons',
      'drug_use_reason_details',
      'drug_use_impact',
      'drug_use_impact_details',
      'reducing_or_stopping_drug_use',
      'reducing_or_stopping_drug_use_details',
      'motivated_stopping_drug_use',
      'drug_use_changes',
      'drug_use_positive_change',
      'drug_use_active_change',
      'drug_use_known_change',
      'drug_use_help_change',
      'drug_use_think_change',
      'drug_use_no_change',
      'drug_use_section_complete',
      'drug_use_analysis_section_complete',
    ],
    next: 'drug-use-type',
    template: 'forms/default',
    backLink: 'drug-use',
    section: 'drug-use',
    sectionProgressRules: [
      { fieldCode: 'drug_use_section_complete', conditionFn: () => 'NO' },
      { fieldCode: 'drug_use_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/drug-use-type': {
    pageTitle: 'Drug use',
    controller: SaveAndContinueController,
    fields: ['drug_use_type', 'other_drug_details', 'drug_use_section_complete', 'drug_use_analysis_section_complete'],
    next: 'drug-usage-details',
    template: 'forms/default',
    backLink: 'drug-use-details',
    section: 'drug-use',
    sectionProgressRules: [
      { fieldCode: 'drug_use_section_complete', conditionFn: () => 'NO' },
      { fieldCode: 'drug_use_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/drug-usage-details': {
    pageTitle: 'Usage details',
    controller: SaveAndContinueController,
    fields: [
      'drug_usage_heroin',
      'past_drug_usage_heroin',
      'drug_usage_methadone_not_prescribed',
      'past_drug_usage_methadone_not_prescribed',
      'drug_usage_crack',
      'past_drug_usage_crack',
      'drug_usage_amphetamines',
      'past_drug_usage_amphetamines',
      'drug_usage_benzodiazepines',
      'past_drug_usage_benzodiazepines',
      'drug_usage_other_drug',
      'past_drug_usage_other_drug',
      'drug_usage_cannabis',
      'past_drug_usage_cannabis',
      'drug_usage_cocaine',
      'past_drug_usage_cocaine',
      'drug_usage_ecstasy',
      'past_drug_usage_ecstasy',
      'drug_usage_ketamine',
      'past_drug_usage_ketamine',
      'drug_usage_methadone_prescribed',
      'past_drug_usage_methadone_prescribed',
      'drug_usage_non_prescribed_medication',
      'past_drug_usage_non_prescribed_medication',
      'drug_usage_psychoactive_substances',
      'past_drug_usage_psychoactive_substances',
      'daily_injecting_drug_heroin',
      'weekly_injecting_drug_heroin',
      'monthly_injecting_drug_heroin',
      'occasionally_injecting_drug_heroin',
      'daily_drug_usage_treatment_heroin',
      'weekly_drug_usage_treatment_heroin',
      'monthly_drug_usage_treatment_heroin',
      'occasionally_drug_usage_treatment',
      'past_injecting_drug_heroin',
      'past_receiving_treatment_heroin',
      'daily_injecting_drug_methadone_not_prescribed',
      'weekly_injecting_drug_methadone_not_prescribed',
      'monthly_injecting_drug_methadone_not_prescribed',
      'occasionally_injecting_drug_methadone_not_prescribed',
      'past_injecting_drug_methadone_not_prescribed',
      'daily_injecting_drug_crack',
      'weekly_injecting_drug_crack',
      'monthly_injecting_drug_crack',
      'occasionally_injecting_drug_crack',
      'past_injecting_drug_crack',
      'daily_injecting_drug_amphetamines',
      'weekly_injecting_drug_amphetamines',
      'monthly_injecting_drug_amphetamines',
      'occasionally_injecting_drug_amphetamines',
      'past_injecting_drug_amphetamines',
      'daily_injecting_drug_benzodiazepines',
      'weekly_injecting_drug_benzodiazepines',
      'monthly_injecting_drug_benzodiazepines',
      'occasionally_injecting_drug_benzodiazepines',
      'past_injecting_drug_benzodiazepines',
      'daily_injecting_drug_other_drug',
      'weekly_injecting_drug_other_drug',
      'monthly_injecting_drug_other_drug',
      'occasionally_injecting_drug_other_drug',
      'past_injecting_drug_other_drug',
      'drug_use_section_complete',
      'drug_use_analysis_section_complete',
    ],
    next: 'drug-use-analysis',
    template: 'forms/sbna-poc/drug-usage',
    backLink: 'drug-use-type',
    section: 'drug-use',
    sectionProgressRules: [
      { fieldCode: 'drug_use_section_complete', conditionFn: () => 'YES' },
      { fieldCode: 'drug_use_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/drug-use-analysis': {
    pageTitle: 'Drug use',
    controller: SaveAndContinueController,
    fields: [
      'drugs_practitioner_analysis_patterns_of_behaviour',
      'drugs_practitioner_analysis_patterns_of_behaviour_details',
      'drugs_practitioner_analysis_strengths_or_protective_factors',
      'drugs_practitioner_analysis_strengths_or_protective_factors_details',
      'drugs_practitioner_analysis_risk_of_serious_harm',
      'drugs_practitioner_analysis_risk_of_serious_harm_details',
      'drugs_practitioner_analysis_risk_of_reoffending',
      'drugs_practitioner_analysis_risk_of_reoffending_details',
      'drugs_practitioner_analysis_related_to_risk',
      'drugs_practitioner_analysis_related_to_risk_details',
      'drug_use_analysis_section_complete',
    ],
    next: 'drug-use-analysis-complete#practitioner-analysis',
    template: 'forms/sbna-poc/drugs-summary-analysis',
    section: 'drug-use',
    sectionProgressRules: [{ fieldCode: 'drug_use_analysis_section_complete', conditionFn: () => 'YES' }],
  },
  '/drug-use-analysis-complete': {
    pageTitle: 'Drug use',
    controller: SaveAndContinueController,
    fields: [],
    template: 'forms/sbna-poc/drugs-summary-analysis-complete',
    section: 'drug-use',
  },
}

export default stepOptions
