import FormWizard from 'hmpo-form-wizard'
import SaveAndContinueController from '../controllers/saveAndContinueController'

const stepOptions: FormWizard.Steps = {
  '/finance': {
    pageTitle: 'Finance',
    controller: SaveAndContinueController,
    fields: [
      'finance_income',
      'finance_bank_account',
      'finance_money_management',
      'finance_gambling',
      'finance_debt',
      'changes_to_finance',
      'finance_no_change_details',
      'finance_thinking_change_details',
      'finance_help_change_details',
      'finance_known_change_details',
      'finance_active_change_details',
      'finance_positive_change_details',
      'unknown_debt_details',
      'yes_someone_elses_formal_debt_to_others_details',
      'yes_someone_elses_debt_to_others_details',
      'yes_someone_elses_formal_debt_details',
      'yes_someone_elses_type_of_debt',
      'yes_formal_debt_to_others_details',
      'yes_debt_to_others_details',
      'yes_formal_debt_details',
      'yes_type_of_debt',
      'unknown_gambling_details',
      'no_gambling_details',
      'yes_someone_elses_gambling_details',
      'yes_their_gambling_details',
      'bad_money_management_details',
      'fairly_bad_money_management_details',
      'fairly_good_money_management_details',
      'good_money_management_details',
      'other_income_details',
      'family_or_friends_details',
      'finance_section_complete',
      'finance_analysis_section_complete',
    ],
    navigationOrder: 3,
    next: 'finance-summary-analysis',
    template: 'forms/default',
    section: 'finance',
    sectionProgressRules: [
      {
        fieldCode: 'finance_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
      { fieldCode: 'finance_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/finance-summary-analysis': {
    pageTitle: 'Finance',
    controller: SaveAndContinueController,
    fields: [
      'finance_practitioner_analysis_patterns_of_behaviour',
      'finance_practitioner_analysis_patterns_of_behaviour_details',
      'finance_practitioner_analysis_strengths_or_protective_factors',
      'finance_practitioner_analysis_strengths_or_protective_factors_details',
      'finance_practitioner_analysis_risk_of_serious_harm',
      'finance_practitioner_analysis_risk_of_serious_harm_details',
      'finance_practitioner_analysis_risk_of_reoffending',
      'finance_practitioner_analysis_risk_of_reoffending_details',
      'finance_practitioner_analysis_related_to_risk',
      'finance_practitioner_analysis_related_to_risk_details',
      'finance_analysis_section_complete',
    ],
    next: 'finance-analysis-complete#practitioner-analysis',
    template: 'forms/sbna-poc/finance-summary-analysis',
    section: 'finance',
    sectionProgressRules: [
      {
        fieldCode: 'finance_analysis_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
    ],
  },
  '/finance-analysis-complete': {
    pageTitle: 'Finance',
    controller: SaveAndContinueController,
    fields: [],
    next: 'drug-use',
    template: 'forms/sbna-poc/finance-analysis-complete',
    section: 'finance',
  },
}

export default stepOptions
