import FormWizard, { FieldType, ValidationType } from 'hmpo-form-wizard'

const immigrationAccommodationHint = `
    <div class="govuk-!-width-two-thirds">
      <p class="govuk-hint">This includes:</p>
      <ul class="govuk-hint govuk-list govuk-list--bullet">
        <li>Schedule 10 - Home Office provides accommodation under the Immigration Act 2016</li>
        <li>Schedule 4 - Home Office provides accommodation for those on immigration bail, prior to the Immigration Act 2016</li>
      </ul>
    </div>
  `

const currentAccommodationHint = `
    <details class="govuk-details" data-module="govuk-details">
      <summary class="govuk-details__summary">
        <span class="govuk-details__summary-text">
          Help if accommodation is a caravan or living vehicle
        </span>
      </summary>
      <div class="govuk-details__text">
        <p>If they're in a caravan or a living vehicle legally, select 'Settled' or 'Temporary'.</p>

        <p>If they're not in a legal place, select 'No accommodation'.</p>
      </div>
    </details>
  `

const suitableHousingConcernsOptions = [
  { text: 'Safety of accommodation', value: 'SAFETY' },
  { text: 'Overcrowding', value: 'OVERCROWDING' },
  { text: 'Victim lives with them', value: 'LIVES_WITH_VICTIM' },
  { text: 'Victimised by someone living with them', value: 'VICTIMISATION' },
  { text: 'Inappropriate amenities or facilities', value: 'FACILITIES' },
  { text: 'Risk of accommodation exploited - for example, cuckooing', value: 'EXPLOITATION' },
  { text: 'Other', value: 'OTHER' },
]

const fields: FormWizard.Fields = {
  current_accommodation: {
    text: "What is [subject]'s current accommodation?",
    hint: { html: currentAccommodationHint, kind: 'html' },
    code: 'current_accommodation',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Current accommodation is required' }],
    options: [
      { text: 'Settled', value: 'SETTLED' },
      { text: 'Temporary', value: 'TEMPORARY' },
      { text: 'No accommodation', value: 'NO_ACCOMMODATION' },
    ],
  },
  type_of_settled_accommodation: {
    text: 'What is the type of settled accommodation?',
    code: 'type_of_settled_accommodation',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Homeowner', value: 'HOMEOWNER' },
      { text: 'Renting privately', value: 'RENTING_PRIVATELY' },
      { text: 'Renting from social, local authority or other', value: 'RENTING_OTHER' },
      { text: 'Living with friends or family', value: 'FRIENDS_OR_FAMILY' },
      { text: 'Supported accommodation', value: 'SUPPORTED_ACCOMMODATION' },
      { text: 'Residential healthcare', value: 'RESIDENTIAL_HEALTHCARE' },
    ],
    dependent: {
      field: 'current_accommodation',
      value: 'SETTLED',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  type_of_temporary_accommodation: {
    text: 'What is the type of temporary accommodation?',
    code: 'type_of_temporary_accommodation',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Short term accommodation', value: 'SHORT_TERM' },
      { text: 'Approved premises', value: 'APPROVED_PREMISES' },
      { text: 'Community Accommodation Service Tier 2 (CAS2)', value: 'CAS2' },
      { text: 'Community Accommodation Service Tier 3 (CAS3)', value: 'CAS3' },
      { text: 'Immigration accommodation', value: 'IMMIGRATION', hint: { html: immigrationAccommodationHint } },
    ],
    dependent: {
      field: 'current_accommodation',
      value: 'TEMPORARY',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  short_term_accommodation_end_date: {
    text: 'Enter expected end date (optional)',
    code: 'short_term_accommodation_end_date',
    type: FieldType.Date,
    dependent: {
      field: 'type_of_temporary_accommodation',
      value: 'SHORT_TERM',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  approved_premises_end_date: {
    text: 'Enter expected end date (optional)',
    code: 'approved_premises_end_date',
    type: FieldType.Date,
    dependent: {
      field: 'type_of_temporary_accommodation',
      value: 'APPROVED_PREMISES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  cas2_end_date: {
    text: 'Enter expected end date (optional)',
    code: 'cas2_end_date',
    type: FieldType.Date,
    dependent: {
      field: 'type_of_temporary_accommodation',
      value: 'CAS2',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  cas3_end_date: {
    text: 'Enter expected end date (optional)',
    code: 'cas3_end_date',
    type: FieldType.Date,
    dependent: {
      field: 'type_of_temporary_accommodation',
      value: 'CAS3',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  immigration_accommodation_end_date: {
    text: 'Enter expected end date (optional)',
    code: 'immigration_accommodation_end_date',
    type: FieldType.Date,
    dependent: {
      field: 'type_of_temporary_accommodation',
      value: 'IMMIGRATION',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  type_of_no_accommodation: {
    text: 'What is the type of accommodation?',
    code: 'type_of_no_accommodation',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Campsite', value: 'CAMPSITE' },
      { text: 'Shelter', value: 'SHELTER' },
      { text: 'Rough sleeping', value: 'ROUGH_SLEEPING' },
      { text: 'Homeless - includes squatting', value: 'HOMELESS' },
      { text: 'Emergency hostel', value: 'EMERGENCY_HOSTEL' },
      { text: 'Awaiting assessment', value: 'AWAITING_ASSESSMENT' },
    ],
    dependent: {
      field: 'current_accommodation',
      value: 'NO_ACCOMMODATION',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  awaiting_assessment_details: {
    text: 'Give details',
    code: 'awaiting_assessment_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'type_of_no_accommodation',
      value: 'AWAITING_ASSESSMENT',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  living_with: {
    text: 'Who is [subject] living with?',
    hint: { text: 'Select all that apply.', kind: 'text' },
    code: 'living_with',
    type: FieldType.CheckBox,
    multiple: true,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Family', value: 'FAMILY' },
      { text: 'Friends', value: 'FRIENDS' },
      { text: 'Partner', value: 'PARTNER' },
      { text: 'Child under 18 years old', value: 'CHILD_UNDER_18' },
      { text: 'Other', value: 'OTHER' },
      { text: 'Alone', value: 'ALONE' },
    ],
  },
  living_with_children_details: {
    text: 'Give details (optional)',
    code: 'living_with_children_details',
    type: FieldType.TextArea,
    dependent: {
      field: 'living_with',
      value: 'CHILD_UNDER_18',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  living_with_partner_details: {
    text: 'Give details (optional)',
    code: 'living_with_partner_details',
    type: FieldType.TextArea,
    dependent: {
      field: 'living_with',
      value: 'PARTNER',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  // living_with_children: {
  //   text: 'Placeholder',
  //   code: 'living_with_children',
  //   type: FieldType.Collection,
  //   dependent: {
  //     field: 'living_with',
  //     value: 'CHILD_UNDER_18',
  //     displayInline: true,
  //   },
  // },
  // living_with_partner: {
  //   text: 'Placeholder',
  //   code: 'living_with_partner',
  //   type: FieldType.Collection,
  //   dependent: {
  //     field: 'living_with',
  //     value: 'PARTNER',
  //     displayInline: true,
  //   },
  // },
  living_with_other: {
    text: 'Give details (optional)',
    code: 'living_with_other',
    type: FieldType.TextArea,
    dependent: {
      field: 'living_with',
      value: 'OTHER',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  suitable_housing: {
    text: "Is [subject]'s overall accommodation suitable?",
    code: 'suitable_housing',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'Yes, with concerns', value: 'YES_WITH_CONCERNS' },
      { text: 'No', value: 'NO' },
    ],
  },
  suitable_housing_concerns: {
    text: 'Select all that apply (optional)',
    code: 'suitable_housing_concerns',
    type: FieldType.CheckBox,
    multiple: true,
    options: suitableHousingConcernsOptions,
    dependent: {
      field: 'suitable_housing',
      value: 'YES_WITH_CONCERNS',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  suitable_housing_concerns_other_details: {
    text: 'Give details',
    code: 'suitable_housing_concerns_other_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'suitable_housing_concerns',
      value: 'OTHER',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  unsuitable_housing_concerns: {
    text: 'Select all that apply (optional)',
    code: 'unsuitable_housing_concerns',
    type: FieldType.CheckBox,
    multiple: true,
    options: suitableHousingConcernsOptions,
    dependent: {
      field: 'suitable_housing',
      value: 'NO',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  unsuitable_housing_concerns_other_details: {
    text: 'Give details',
    code: 'unsuitable_housing_concerns_other_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'unsuitable_housing_concerns',
      value: 'OTHER',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  suitable_housing_location: {
    text: "Is the location of [subject]'s accommodation suitable?",
    code: 'suitable_housing_location',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  suitable_housing_location_concerns: {
    text: 'Select all that apply (optional)',
    code: 'suitable_housing_location_concerns',
    type: FieldType.CheckBox,
    multiple: true,
    options: [
      { text: 'Safety of the area', value: 'AREA_SAFETY' },
      { text: 'Close to criminal associates', value: 'CRIMINAL_ASSOCIATES' },
      { text: 'Difficulty with neighbours', value: 'NEIGHBOUR_DIFFICULTY' },
      { text: 'Close to victim or possible victims', value: 'VICTIM_PROXIMITY' },
      { text: 'Close to someone who has victimised them', value: 'VICTIMISATION' },
      { text: 'Honour-based perpetrator or victim', value: 'HONOUR_BASED' },
      { text: 'Other', value: 'OTHER' },
    ],
    dependent: {
      field: 'suitable_housing_location',
      value: 'NO',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  suitable_housing_location_concerns_other_details: {
    text: 'Give details',
    code: 'suitable_housing_location_concerns_other_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'suitable_housing_location_concerns',
      value: 'OTHER',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  no_accommodation_reason: {
    text: 'Why does [subject] have no accommodation?',
    hint: { text: 'Consider current and past homelessness issues', kind: 'text' },
    code: 'no_accommodation_reason',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Financial difficulties', value: 'FINANCIAL_DIFFICULTIES' },
      { text: 'Alcohol related problems', value: 'ALCOHOL_PROBLEMS' },
      { text: 'Drug related problems', value: 'DRUG_PROBLEMS' },
      { text: 'No accommodation when released from prison', value: 'PRISON_RELEASE' },
      { text: 'Left previous accommodation for their own safety', value: 'SAFETY' },
      { text: 'Left previous accommodation due to risk to others', value: 'RISK_TO_OTHERS' },
      { text: 'Other', value: 'OTHER' },
    ],
  },
  no_accommodation_reason_other_details: {
    text: 'Give details',
    code: 'no_accommodation_reason_other_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'no_accommodation_reason',
      value: 'OTHER',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  past_accommodation_details: {
    text: 'What has helped [subject] stay in accommodation in the past?',
    code: 'past_accommodation_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  },
  suitable_housing_details: {
    text: "What's helped [subject] stay in suitable housing in the past?",
    code: 'suitable_housing_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'current_accommodation',
      value: 'NO_ACCOMMODATION',
    },
  },
  suitable_housing_planned: {
    text: 'Does [subject] have future accommodation planned?',
    code: 'suitable_housing_planned',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Awaiting assessment', value: 'AWAITING_ASSESSMENT' },
      { text: 'Awaiting placement', value: 'AWAITING_PLACEMENT' },
      { text: 'Buying a house', value: 'BUYING_HOUSE' },
      { text: 'Rent privately', value: 'RENT_PRIVATELY' },
      { text: 'Rent from social, local authority or other', value: 'RENT_SOCIAL' },
      { text: 'Living with friends or family', value: 'LIVING_WITH_FRIENDS_OR_FAMILY' },
      { text: 'Supported accommodation', value: 'SUPPORTED_ACCOMMODATION' },
      { text: 'Residential healthcare', value: 'RESIDENTIAL_HEALTHCARE' },
      { text: 'Other', value: 'OTHER' },
    ],
  },
  suitable_housing_planned_awaiting_assessment_details: {
    text: 'Give details',
    code: 'suitable_housing_planned_awaiting_assessment_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'suitable_housing_planned',
      value: 'AWAITING_ASSESSMENT',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  awaiting_accommodation_placement_details: {
    text: 'Give details',
    code: 'awaiting_accommodation_placement_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'suitable_housing_planned',
      value: 'AWAITING_PLACEMENT',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  suitable_housing_planned_other_details: {
    text: 'Give details',
    hint: { text: 'Include where and who with', kind: 'text' },
    code: 'suitable_housing_planned_other_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'suitable_housing_planned',
      value: 'OTHER',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  accommodation_changes: {
    text: 'Does [subject] want to make changes to their accommodation?',
    hint: { text: 'This question must be directly answered by [subject]', kind: 'text' },
    code: 'accommodation_changes',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'I have already made changes and want to maintain them', value: 'MADE_CHANGES' },
      { text: 'I am actively making changes', value: 'MAKING_CHANGES' },
      { text: 'I want to make changes and know how to', value: 'WANT_TO_MAKE_CHANGES' },
      { text: 'I want to make changes but need help', value: 'NEEDS_HELP_TO_MAKE_CHANGES' },
      { text: 'I am thinking about making changes', value: 'THINKING_ABOUT_MAKING_CHANGES' },
      { text: 'I do not want to make changes', value: 'DOES_NOT_WANT_TO_MAKE_CHANGES' },
      { text: 'I do not want to answer', value: 'DOES_NOT_WANT_TO_ANSWER' },
      { text: '[subject] is not present', value: 'NOT_PRESENT' },
      { text: 'Not applicable', value: 'NOT_APPLICABLE' },
    ],
  },
  accommodation_made_changes_details: {
    text: 'Give details',
    code: 'accommodation_made_changes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'accommodation_changes',
      value: 'MADE_CHANGES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  accommodation_making_changes_details: {
    text: 'Give details',
    code: 'accommodation_making_changes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'accommodation_changes',
      value: 'MAKING_CHANGES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  accommodation_want_to_make_changes_details: {
    text: 'Give details',
    code: 'accommodation_want_to_make_changes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'accommodation_changes',
      value: 'WANT_TO_MAKE_CHANGES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  accommodation_needs_help_to_make_changes_details: {
    text: 'Give details',
    code: 'accommodation_needs_help_to_make_changes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'accommodation_changes',
      value: 'NEEDS_HELP_TO_MAKE_CHANGES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  accommodation_thinking_about_making_changes_details: {
    text: 'Give details',
    code: 'accommodation_thinking_about_making_changes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'accommodation_changes',
      value: 'THINKING_ABOUT_MAKING_CHANGES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  accommodation_does_not_want_to_make_changes_details: {
    text: 'Give details',
    code: 'accommodation_does_not_want_to_make_changes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'accommodation_changes',
      value: 'DOES_NOT_WANT_TO_MAKE_CHANGES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  accommodation_practitioner_analysis: {
    text: 'Practitioner analysis',
    hint: {
      text: 'Include any strengths, needs or risks which may link to risk of serious harm or risk of reoffending.',
      kind: 'text',
    },
    code: 'accommodation_practitioner_analysis',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    characterCountMax: 4000,
  },
  accommodation_serious_harm: {
    text: "Is [subject]'s accommodation linked to risk of serious harm?",
    code: 'accommodation_serious_harm',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'yes' },
      { text: 'No', value: 'no' },
    ],
    characterCountMax: 4000,
  },
  accommodation_risk_of_reoffending: {
    text: "Is [subject]'s accommodation linked to risk of reoffending?",
    code: 'accommodation_risk_of_reoffending',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'yes' },
      { text: 'No', value: 'no' },
    ],
    characterCountMax: 4000,
  },
  drug_use: {
    text: 'Has [subject] ever used drugs?',
    code: 'drug_use',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Drug use is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  drug_use_changes: {
    text: 'Does [subject] want to make changes to their drug use?',
    code: 'drug_use_changes',
    hint: { text: 'This question must be directly answered by [subject] ', kind: 'text' },
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Drug use change field is required' }],
    options: [
      { text: 'I have already made positive changes', value: 'POSITIVE_CHANGE' },
      { text: 'I am actively making changes', value: 'ACTIVE_CHANGE' },
      { text: 'I want to make changes and know how to', value: 'KNOWN_CHANGE' },
      { text: 'I want to make changes but need help', value: 'HELP_CHANGE' },
      { text: 'I am thinking about making changes', value: 'THINK_CHANGE' },
      { text: 'I do not want to make changes', value: 'NO_CHANGE' },
      { text: 'I do not want to answer', value: 'NO_ANSWER_CHANGE' },
      { text: '[subject] is not present', value: 'NOT_PRESENT' },
      { text: 'Not applicable', value: 'NOT_APPLICABLE' },
    ],
  },
  drug_use_positive_change: {
    text: 'Give details',
    code: 'drug_use_positive_change',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'POSITIVE_CHANGE',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  drug_use_active_change: {
    text: 'Give details',
    code: 'drug_use_active_change',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'ACTIVE_CHANGE',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  drug_use_known_change: {
    text: 'Give details',
    code: 'drug_use_known_change',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'KNOWN_CHANGE',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  drug_use_help_change: {
    text: 'Give details',
    code: 'drug_use_help_change',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'HELP_CHANGE',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  drug_use_think_change: {
    text: 'Give details',
    code: 'drug_use_think_change:',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'THINK_CHANGE',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  drug_use_no_change: {
    text: 'Give details',
    code: 'drug_use_no_change:',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'NO_CHANGE',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  // child_name: {
  //   text: 'Name',
  //   code: 'child_name',
  //   type: FieldType.Text,
  //   validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  // },
  // child_date_of_birth: {
  //   text: 'Date of birth',
  //   hint: { text: 'For example, 31 3 2011' },
  //   code: 'child_date_of_birth',
  //   type: FieldType.Date,
  //   validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  // },
  // child_age: {
  //   text: 'Age',
  //   code: 'child_age',
  //   type: FieldType.Text,
  //   validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  // },
  // relationship_to_child: {
  //   text: "Select [subject]'s relationship to the child",
  //   code: 'relationship_to_child',
  //   type: FieldType.Radio,
  //   validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  //   options: [
  //     { text: 'Parent or carer', value: 'PARENT_OR_CARER' },
  //     { text: 'Family member', value: 'FAMILY_MEMBER' },
  //     { text: 'Friend', value: 'FRIEND' },
  //     { text: 'Other', value: 'OTHER' },
  //   ],
  // },
  // child_gender: {
  //   text: 'Select gender',
  //   code: 'child_gender',
  //   type: FieldType.Radio,
  //   validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  //   options: [
  //     { text: 'Boy', value: 'BOY' },
  //     { text: 'Girl', value: 'GIRL' },
  //     { text: 'Non-binary', value: 'NON_BINARY' },
  //     { text: 'Prefer not to say', value: 'PREFER_NOT_TO_SAY' },
  //   ],
  // },
  // partner_name: {
  //   text: 'Name',
  //   code: 'partner_name',
  //   type: FieldType.Text,
  //   validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  // },
  // partner_age: {
  //   text: 'Age',
  //   code: 'partner_age',
  //   type: FieldType.Text,
  //   validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  // },
  // partner_gender: {
  //   text: 'Select gender',
  //   code: 'partner_gender',
  //   type: FieldType.Radio,
  //   validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  //   options: [
  //     { text: 'Boy', value: 'BOY' },
  //     { text: 'Girl', value: 'GIRL' },
  //     { text: 'Non-binary', value: 'NON_BINARY' },
  //     { text: 'Prefer not to say', value: 'PREFER_NOT_TO_SAY' },
  //   ],
  // },
  drug_use_type: {
    text: 'Which drugs have [subject] used?',
    code: 'drug_use_type',
    hint: { text: 'Include current and previous drugs. Select all that apply.', kind: 'text' },
    type: FieldType.CheckBox,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Amphetamines', value: 'AMPHETAMINES' },
      { text: 'Benzodiazepines', value: 'BENZODIAZEPINES' },
      { text: 'Cannabis', value: 'CANNABIS' },
      { text: 'Cocaine', value: 'COCAINE' },
      { text: 'Crack', value: 'CRACK' },
      { text: 'Ecstasy', value: 'ECSTASY' },
      { text: 'Heroin', value: 'HEROIN' },
      { text: 'Methadone (not prescribed)', value: 'METHADONE_NOT_PRESCRIBED' },
      { text: 'Methadone (prescribed)', value: 'METHADONE_PRESCRIBED' },
      { text: 'Non-prescribed medication', value: 'NON_PRESCRIBED_MEDICATION' },
      { text: 'Psychoactive substances (spice)', value: 'PSYCHOACTIVE_SUBSTANCES_SPICE' },
      { text: 'Other', value: 'OTHER_DRUG_TYPE' },
    ],
  },
  drug_usage: {
    text: 'How often is [subject] using this drug?',
    code: 'drug_usage',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Daily', value: 'DAILY' },
      { text: 'Weekly', value: 'WEEKLY' },
      { text: 'Monthly', value: 'MONTHLY' },
      { text: 'Occasionally', value: 'OCCASIONALLY' },
      { text: 'Not currently using this drug', value: 'NO_CURRENT_USAGE' },
    ],
  },
  drug_usage_heroin: {
    text: 'How often is [subject] using this drug?',
    code: 'drug_usage_heroin',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Daily', value: 'DAILY' },
      { text: 'Weekly', value: 'WEEKLY' },
      { text: 'Monthly', value: 'MONTHLY' },
      { text: 'Occasionally', value: 'OCCASIONALLY' },
      { text: 'Not currently using this drug', value: 'NO_CURRENT_USAGE' },
    ],
  },
  daily_drug_usage_treatment: {
    text: 'Is [subject] receiving treatment?',
    code: 'daily_drug_usage_treatment',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
    dependent: {
      field: 'drug_usage_heroin',
      value: 'DAILY',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  weekly_drug_usage_treatment: {
    text: 'Is [subject] receiving treatment?',
    code: 'weekly_drug_usage_treatment',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
    dependent: {
      field: 'drug_usage_heroin',
      value: 'WEEKLY',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  monthly_drug_usage_treatment: {
    text: 'Is [subject] receiving treatment?',
    code: 'monthly_drug_usage_treatment',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
    dependent: {
      field: 'drug_usage_heroin',
      value: 'MONTHLY',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  occasionally_drug_usage_treatment: {
    text: 'Is [subject] receiving treatment?',
    code: 'occasionally_drug_usage_treatment',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
    dependent: {
      field: 'drug_usage_heroin',
      value: 'OCCASIONALLY',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  drug_past_usage: {
    text: 'Has [subject] used this drug in the past?',
    code: 'drug_past_usage',
    type: FieldType.CheckBox,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  drug_use_reasons: {
    text: 'Why did [subject] start using drugs?',
    hint: { text: 'Consider their history and any triggers of drug use. Select all that apply', kind: 'text' },
    code: 'drug_use_reasons',
    type: FieldType.CheckBox,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Recreation or pleasure', value: 'RECREATION_PLEASURE' },
      { text: 'Curiosity or experimentation', value: 'CURIOSITY_EXPERIMENTATION' },
      { text: 'Manage stress or emotional issues', value: 'STRESS_EMOTIONAL_ISSUES' },
      { text: 'Self-medication for pain', value: 'SELF_MEDICATION_PAIN' },
      { text: 'Manage withdrawal symptoms', value: 'MANAGE_WITHDRAWAL' },
      { text: 'Peer pressure or social influence', value: 'SOCIAL_PEER_PRESSURE' },
      { text: 'Enhance performance', value: 'ENHANCE_PERFORMANCE' },
      { text: 'Escapism or avoidance', value: 'ESCAPISM_AVOIDANCE' },
      { text: 'Cultural or religious practices', value: 'CULTURAL_RELIGIOUS' },
      { text: 'Other', value: 'OTHER' },
    ],
  },
  drug_use_reason_details: {
    text: 'Give details',
    code: 'drug_use_reason_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_reasons',
      value: 'OTHER',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  drug_use_impact: {
    text: "What's the impact of [subject] using drugs?",
    hint: { text: 'Select all that apply', kind: 'text' },
    code: 'drug_use_impact',
    type: FieldType.CheckBox,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Physical or mental health', value: 'PHYSICAL_MENTAL_HEALTH', hint: { text: 'Includes overdose.' } },
      {
        text: 'Relationships',
        value: 'RELATIONSHIPS',
        hint: { text: 'Includes isolation or neglecting responsibilities.' },
      },
      { text: 'Finances', value: 'FINANCES', hint: { text: 'Includes having no money.' } },
      {
        text: 'Community',
        value: 'COMMUNITY',
        hint: { text: 'Includes limited opportunities or judgement from others.' },
      },
      {
        text: 'Behavioural',
        value: 'BEHAVIOURAL',
        hint: { text: 'Includes unemployment, disruption on education or lack of productivity.' },
      },
      { text: 'Links to offending', value: 'OFFENDING' },
      { text: 'Other', value: 'OTHER' },
    ],
  },
  drug_use_impact_details: {
    text: 'Give details',
    hint: { text: 'Consider impact on themselves or others.', kind: 'text' },
    code: 'drug_use_impact_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_impact',
      value: 'OTHER',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  reducing_or_stopping_drug_use: {
    text: 'Has anything helped [subject] to stop or reduce using drugs in the past?',
    code: 'reducing_or_stopping_drug_use',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  reducing_or_stopping_drug_use_details: {
    text: 'Give details',
    code: 'reducing_or_stopping_drug_use_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'reducing_or_stopping_drug_use',
      value: 'YES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  motivated_stopping_drug_use: {
    text: 'Is [subject] motivated to stop or reduce their drug use?',
    code: 'motivated_stopping_drug_use',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Does not show motivation to stop or reduce', value: 'NO_MOTIVATION' },
      { text: 'Shows some motivation to stop or reduce', value: 'SOME_MOTIVATION' },
      { text: 'Motivated to stop or reduce', value: 'MOTIVATED' },
      { text: 'Not applicable', value: 'NOT_APPLICABLE' },
    ],
  },
  patterns_or_behaviours: {
    text: 'Are there any patterns or behaviours related to this area?',
    hint: 'Include repeated circumstances or behaviours.',
    code: 'patterns_or_behaviours',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  patterns_or_behaviours_yes_details: {
    text: 'Give details',
    code: 'patterns_or_behaviours_yes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'patterns_or_behaviours',
      value: 'YES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  patterns_or_behaviours_no_details: {
    text: 'Give details',
    code: 'patterns_or_behaviours_no_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'patterns_or_behaviours',
      value: 'NO',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  strengths_or_protective_factors: {
    text: 'Are there any strengths or protective factors related to this area?',
    hint: 'Include any strategies, people or support networks that helped.',
    code: 'strengths_or_protective_factors',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  strengths_or_protective_factors_yes_details: {
    text: 'Give details',
    code: 'strengths_or_protective_factors_yes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'strengths_or_protective_factors',
      value: 'YES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  strengths_or_protective_factors_no_details: {
    text: 'Give details',
    code: 'strengths_or_protective_factors_no_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'strengths_or_protective_factors',
      value: 'NO',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  linked_to_risk_of_serious_harm: {
    text: 'Is this an area linked to risk of serious harm?',
    code: 'linked_to_risk_of_serious_harm',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  linked_to_risk_of_serious_harm_yes_details: {
    text: 'Give details',
    code: 'linked_to_risk_of_serious_harm_yes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'linked_to_risk_of_serious_harm',
      value: 'YES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  linked_to_risk_of_serious_harm_no_details: {
    text: 'Give details',
    code: 'linked_to_risk_of_serious_harm_no_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'linked_to_risk_of_serious_harm',
      value: 'NO',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  linked_to_risk_of_reoffending: {
    text: 'Is this an area linked to risk of reoffedning?',
    code: 'linked_to_risk_of_reoffending',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  linked_to_risk_of_reoffending_yes_details: {
    text: 'Give details',
    code: 'linked_to_risk_of_reoffending_yes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'linked_to_risk_of_reoffending',
      value: 'YES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  linked_to_risk_of_reoffending_no_details: {
    text: 'Give details',
    code: 'linked_to_risk_of_reoffending_no_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'linked_to_risk_of_reoffending',
      value: 'NO',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  not_related_to_risk: {
    text: 'Is this an area of need which is not related to risk?',
    code: 'not_related_to_risk',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  not_related_to_risk_yes_details: {
    text: 'Give details',
    code: 'not_related_to_risk_yes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'not_related_to_risk',
      value: 'YES',
      displayInline: true,
    },
    useSmallLabel: true,
  },
  not_related_to_risk_no_details: {
    text: 'Give details',
    code: 'not_related_to_risk_no_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'not_related_to_risk',
      value: 'NO',
      displayInline: true,
    },
    useSmallLabel: true,
  },
}
export default fields
