import FormWizard, { FieldType, ValidationType } from 'hmpo-form-wizard'

const fields: FormWizard.Fields = {
  current_accommodation: {
    text: "What is [subject]'s current accommodation?",
    code: 'current_accommodation',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Current accommodation is required' }],
    options: [
      { text: 'Settled', value: 'SETTLED' },
      { text: 'Temporary', value: 'TEMPORARY' },
      { text: 'No accommodation', value: 'NO_ACCOMMODATION' },
    ],
  },
  living_with: {
    text: 'Who does [subject] live with?',
    code: 'living_with',
    type: FieldType.CheckBox,
    multiple: true,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Family', value: 'FAMILY' },
      { text: 'Friends', value: 'FRIENDS' },
      { text: 'Partner', value: 'PARTNER' },
      { text: 'Child under 18 years old', value: 'CHILD_UNDER_18' },
      { text: 'Alone', value: 'ALONE' },
      { text: 'Other', value: 'OTHER' },
    ],
  },
  suitable_housing: {
    text: "Is [subject]'s housing suitable?",
    code: 'suitable_housing',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  suitable_housing_location: {
    text: "Is the location of [subject]'s housing suitable?",
    code: 'suitable_housing_location',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  no_accommodation_details: {
    text: 'Why does [subject] have no housing?',
    code: 'no_accommodation_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    // dependent: {
    //   field: 'current_accommodation',
    //   value: 'NO_ACCOMMODATION',
    // },
  },
  suitable_housing_details: {
    text: "What's helped [subject] stay in suitable housing in the past?",
    code: 'suitable_housing_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  },
  suitable_housing_planned: {
    text: 'Does [subject] have future housing planned?',
    code: 'suitable_housing_planned',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
      { text: 'Awaiting assessment', value: 'AWAITING_ASSESSMENT' },
      { text: 'Awaiting placement', value: 'AWAITING_PLACEMENT' },
    ],
  },
  awaiting_accommodation_placement_details: {
    text: 'Give details',
    code: 'awaiting_accommodation_placement_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'suitable_housing_planned',
      value: 'AWAITING_PLACEMENT',
      displayInline: true,
    },
  },
  accommodation_changes: {
    text: 'Do you want to make changes to your housing?',
    hint: 'This question must be answered by [subject]',
    code: 'accommodation_changes',
    type: FieldType.CheckBox,
    multiple: true,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'I want to make changes', value: 'I_WANT_TO_MAKE_CHANGES' },
      { text: 'I want to make changes but need help', value: 'I_NEED_HELP_TO_MAKE_CHANGES' },
      { text: 'I do not want to make changes', value: 'I_DO_NOT_WANT_TO_MAKE_CHANGES' },
      { text: 'I do not think I can make changes right now', value: 'I_AM_UNABLE_TO_MAKE_CHANGES_CURRENTLY' },
      { text: '[subject] is not present or did not want to answer', value: 'NOT_PRESENT_OR_DID_NOT_ANSWER' },
    ],
  },
  accommodation_changes_details: {
    text: 'What changes do you want to achieve or maintain?',
    hint: 'This question must be answered by [subject]',
    code: 'accommodation_changes_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  },
  accommodation_practitioner_analysis: {
    text: 'Practitioner analysis',
    hint: 'Include any strengths, needs or risks which may link to risk of serious harm or risk of reoffending.',
    code: 'accommodation_practitioner_analysis',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
  },
  accommodation_serious_harm: {
    text: "Is [subject]'s accommodation linked to risk of serious harm?",
    code: 'accommodation_serious_harm',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'yes' },
      { text: 'No', value: 'no' },
    ],
  },
  accommodation_risk_of_reoffending: {
    text: "Is [subject]'s accommodation linked to risk of reoffending?",
    code: 'accommodation_risk_of_reoffending',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'yes' },
      { text: 'No', value: 'no' },
    ],
  },
  drug_use: {
    text: 'Has [subject] ever used drugs?',
    code: 'drug_use',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Drug use is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  drug_use_changes: {
    text: 'Does [subject] want to make changes to their drug use?',
    code: 'drug_use_changes',
    hint: 'This question must be directly answered by [Subject] ',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Drug use change field is required' }],
    options: [
      { text: 'I have already made positive changes', value: 'POSITIVE_CHANGE' },
      { text: 'I am actively making changes', value: 'ACTIVE_CHANGE' },
      { text: 'I want to make changes and know how to', value: 'KNOWN_CHANGE' },
      { text: 'I want to make changes but need help', value: 'HELP_CHANGE' },
      { text: 'I am thinking about making changes', value: 'THINK_CHANGE' },
      { text: 'I do not want to make changes', value: 'NO_CHANGE' },
      { text: 'I do not want to answer', value: 'NO_ANSWER_CHANGE' },
      { text: '[subject] is not present', value: 'NOT_PRESENT' },
      { text: 'Not applicable', value: 'NOT_APPLICABLE' },
    ],
  },
  drug_use_positive_change: {
    text: 'Give details',
    code: 'drug_use_positive_change',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'POSITIVE_CHANGE',
      displayInline: true,
    },
  },
  drug_use_active_change: {
    text: 'Give details',
    code: 'drug_use_active_change',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'ACTIVE_CHANGE',
      displayInline: true,
    },
  },
  drug_use_known_change: {
    text: 'Give details',
    code: 'drug_use_known_change',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'KNOWN_CHANGE',
      displayInline: true,
    },
  },
  drug_use_help_change: {
    text: 'Give details',
    code: 'drug_use_help_change',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'HELP_CHANGE',
      displayInline: true,
    },
  },
  drug_use_think_change: {
    text: 'Give details',
    code: 'drug_use_think_change:',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'THINK_CHANGE',
      displayInline: true,
    },
  },
  drug_use_no_change: {
    text: 'Give details',
    code: 'drug_use_no_change:',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_changes',
      value: 'NO_CHANGE',
      displayInline: true,
    },
  },
  drug_use_type: {
    text: 'Which drugs have [subject] used?',
    code: 'drug_use_type',
    hint: 'Include current and previous drugs. Select all that apply.',
    type: FieldType.CheckBox,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Amphetamines', value: 'AMPHETAMINES' },
      { text: 'Benzodiazepines', value: 'BENZODIAZEPINES' },
      { text: 'Cannabis', value: 'CANNABIS' },
      { text: 'Cocaine', value: 'COCAINE' },
      { text: 'Crack', value: 'CRACK' },
      { text: 'Ecstasy', value: 'ECSTASY' },
      { text: 'Heroin', value: 'HEROIN' },
      { text: 'Methadone (not prescribed)', value: 'METHADONE_NOT_PRESCRIBED' },
      { text: 'Methadone (prescribed)', value: 'METHADONE_PRESCRIBED' },
      { text: 'Non-prescribed medication', value: 'NON_PRESCRIBED_MEDICATION' },
      { text: 'Psychoactive substances (spice)', value: 'PSYCHOACTIVE_SUBSTANCES_SPICE' },
      { text: 'Other', value: 'OTHER_DRUG_TYPE' },
    ],
  },
  drug_usage: {
    text: 'How often is [subject] using this drug?',
    code: 'drug_usage',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Daily', value: 'DAILY' },
      { text: 'Weekly', value: 'WEEKLY' },
      { text: 'Monthly', value: 'MONTHLY' },
      { text: 'Occasionally', value: 'OCCASIONALLY' },
      { text: 'Not currently using this drug', value: 'NO_CURRENT_USAGE' },
    ],
  },
  drug_usage_heroin: {
    text: 'How often is [subject] using this drug?',
    code: 'drug_usage_heroin',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Daily', value: 'DAILY' },
      { text: 'Weekly', value: 'WEEKLY' },
      { text: 'Monthly', value: 'MONTHLY' },
      { text: 'Occasionally', value: 'OCCASIONALLY' },
      { text: 'Not currently using this drug', value: 'NO_CURRENT_USAGE' },
    ],
  },
  daily_drug_usage_treatment: {
    text: 'Is [subject] receiving treatment?',
    code: 'daily_drug_usage_treatment',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
    dependent: {
      field: 'drug_usage_heroin',
      value: 'DAILY',
      displayInline: true,
    },
  },
  weekly_drug_usage_treatment: {
    text: 'Is [subject] receiving treatment?',
    code: 'weekly_drug_usage_treatment',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
    dependent: {
      field: 'drug_usage_heroin',
      value: 'WEEKLY',
      displayInline: true,
    },
  },
  monthly_drug_usage_treatment: {
    text: 'Is [subject] receiving treatment?',
    code: 'monthly_drug_usage_treatment',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
    dependent: {
      field: 'drug_usage_heroin',
      value: 'MONTHLY',
      displayInline: true,
    },
  },
  occasionally_drug_usage_treatment: {
    text: 'Is [subject] receiving treatment?',
    code: 'occasionally_drug_usage_treatment',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
    dependent: {
      field: 'drug_usage_heroin',
      value: 'OCCASIONALLY',
      displayInline: true,
    },
  },
  drug_past_usage: {
    text: 'Has [subject] used this drug in the past?',
    code: 'drug_past_usage',
    type: FieldType.CheckBox,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  drug_use_reasons: {
    text: 'Why did [subject] start using drugs?',
    hint: 'Consider their history and any triggers of drug use. Select all that apply',
    code: 'drug_use_reasons',
    type: FieldType.CheckBox,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Recreation or pleasure', value: 'RECREATION_PLEASURE' },
      { text: 'Curiosity or experimentation', value: 'CURIOSITY_EXPERIMENTATION' },
      { text: 'Manage stress or emotional issues', value: 'STRESS_EMOTIONAL_ISSUES' },
      { text: 'Self-medication for pain', value: 'SELF_MEDICATION_PAIN' },
      { text: 'Manage withdrawal symptoms', value: 'MANAGE_WITHDRAWAL' },
      { text: 'Peer pressure or social influence', value: 'SOCIAL_PEER_PRESSURE' },
      { text: 'Enhance performance', value: 'ENHANCE_PERFORMANCE' },
      { text: 'Escapism or avoidance', value: 'ESCAPISM_AVOIDANCE' },
      { text: 'Cultural or religious practices', value: 'CULTURAL_RELIGIOUS' },
      { text: 'Other', value: 'OTHER' },
    ],
  },
  drug_use_reason_details: {
    text: 'Give details',
    code: 'drug_use_reason_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_reasons',
      value: 'OTHER',
      displayInline: true,
    },
  },
  drug_use_impact: {
    text: "What's the impact of [subject] using drugs?",
    hint: 'Select all that apply',
    code: 'drug_use_impact',
    type: FieldType.CheckBox,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Physical or mental health', value: 'PHYSICAL_MENTAL_HEALTH' },
      { text: 'Relationships', value: 'RELATIONSHIPS' },
      { text: 'Finances', value: 'FINANCES' },
      { text: 'Community', value: 'COMMUNITY' },
      { text: 'Behavioural', value: 'BEHAVIOURAL' },
      { text: 'Links to offending', value: 'OFFENDING' },
      { text: 'Other', value: 'OTHER' },
    ],
  },
  drug_use_impact_details: {
    text: 'Give details',
    hint: 'Consider impact on themselves or others.',
    code: 'drug_use_impact_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'drug_use_impact',
      value: 'OTHER',
      displayInline: true,
    },
  },
  reducing_or_stopping_drug_use: {
    text: 'Has anything helped [subject] to stop or reduce using drugs in the past?',
    code: 'reducing_or_stopping_drug_use',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Yes', value: 'YES' },
      { text: 'No', value: 'NO' },
    ],
  },
  reducing_or_stopping_drug_use_details: {
    text: 'Give details',
    code: 'reducing_or_stopping_drug_use_details',
    type: FieldType.TextArea,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    dependent: {
      field: 'reducing_or_stopping_drug_use',
      value: 'YES',
      displayInline: true,
    },
  },
  motivated_stopping_drug_use: {
    text: 'Is [subject] motivated to stop or reduce their drug use?',
    code: 'motivated_stopping_drug_use',
    type: FieldType.Radio,
    validate: [{ type: ValidationType.Required, message: 'Field is required' }],
    options: [
      { text: 'Does not show motivation to stop or reduce', value: 'NO_MOTIVATION' },
      { text: 'Shows some motivation to stop or reduce', value: 'SOME_MOTIVATION' },
      { text: 'Motivated to stop or reduce', value: 'MOTIVATED' },
      { text: 'Not applicable', value: 'NOT_APPLICABLE' },
    ],
  },
}
export default fields
