import FormWizard from 'hmpo-form-wizard'
import SaveAndContinueController from './controllers/saveAndContinueController'
import StartController from './controllers/startController'
// import AddChildController from './controllers/addChildController'
// import EditChildController from './controllers/editChildController'
// import AddPartnerController from './controllers/addPartnerController'
// import EditPartnerController from './controllers/editPartnerController'

const stepOptions: FormWizard.Steps = {
  '/start': {
    pageTitle: 'POC Form',
    controller: StartController,
    reset: true,
    entryPoint: true,
    template: `forms/sbna-poc/start`,
    next: 'accommodation',
    section: 'none',
  },
  '/accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'current_accommodation',
      'type_of_settled_accommodation',
      'type_of_temporary_accommodation',
      'short_term_accommodation_end_date',
      'approved_premises_end_date',
      'cas2_end_date',
      'cas3_end_date',
      'immigration_accommodation_end_date',
      'type_of_no_accommodation',
      'awaiting_assessment_details',
    ],
    next: [
      { field: 'current_accommodation', value: 'SETTLED', next: 'settled-accommodation' },
      { field: 'type_of_temporary_accommodation', value: 'SHORT_TERM', next: 'temporary-accommodation-2' },
      { field: 'type_of_temporary_accommodation', value: 'IMMIGRATION', next: 'temporary-accommodation-2' },
      { field: 'current_accommodation', value: 'TEMPORARY', next: 'temporary-accommodation' },
      { field: 'type_of_no_accommodation', value: 'AWAITING_ASSESSMENT', next: 'no-accommodation-2' },
      { field: 'current_accommodation', value: 'NO_ACCOMMODATION', next: 'no-accommodation' },
    ],
    template: 'forms/default',
    navigationOrder: 1,
    section: 'accommodation',
    sectionProgressRules: [
      { fieldCode: 'accommodation_section_complete', conditionFn: () => 'NO' },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/settled-accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'living_with',
      'living_with_children_details',
      'living_with_partner_details',
      'living_with_other',
      'suitable_housing_location',
      'suitable_housing_location_concerns',
      'suitable_housing_location_concerns_other_details',
      'suitable_housing',
      'suitable_housing_concerns',
      'unsuitable_housing_concerns',
      'suitable_housing_concerns_other_details',
      'accommodation_changes',
      'accommodation_made_changes_details',
      'accommodation_making_changes_details',
      'accommodation_want_to_make_changes_details',
      'accommodation_needs_help_to_make_changes_details',
      'accommodation_thinking_about_making_changes_details',
      'accommodation_does_not_want_to_make_changes_details',
    ],
    next: 'accommodation-summary-analysis-settled',
    template: 'forms/default',
    backLink: 'accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      { fieldCode: 'accommodation_section_complete', conditionFn: (isValid: boolean) => (isValid ? 'YES' : 'NO') },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/temporary-accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'living_with',
      'living_with_children_details',
      'living_with_partner_details',
      'living_with_other',
      'suitable_housing_location',
      'suitable_housing_location_concerns',
      'suitable_housing_location_concerns_other_details',
      'suitable_housing',
      'suitable_housing_concerns',
      'unsuitable_housing_concerns',
      'suitable_housing_concerns_other_details',
      'suitable_housing_planned',
      'future_accommodation_type',
      'suitable_housing_planned_awaiting_assessment_details',
      'awaiting_accommodation_placement_details',
      'suitable_housing_planned_other_details',
      'accommodation_changes',
      'accommodation_made_changes_details',
      'accommodation_making_changes_details',
      'accommodation_want_to_make_changes_details',
      'accommodation_needs_help_to_make_changes_details',
      'accommodation_thinking_about_making_changes_details',
      'accommodation_does_not_want_to_make_changes_details',
    ],
    next: 'accommodation-summary-analysis-temporary',
    template: 'forms/default',
    backLink: 'accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      { fieldCode: 'accommodation_section_complete', conditionFn: (isValid: boolean) => (isValid ? 'YES' : 'NO') },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/temporary-accommodation-2': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'suitable_housing_location',
      'suitable_housing_location_concerns',
      'suitable_housing_location_concerns_other_details',
      'suitable_housing',
      'suitable_housing_concerns',
      'unsuitable_housing_concerns',
      'suitable_housing_concerns_other_details',
      'suitable_housing_planned',
      'future_accommodation_type',
      'suitable_housing_planned_awaiting_assessment_details',
      'awaiting_accommodation_placement_details',
      'suitable_housing_planned_other_details',
      'accommodation_changes',
      'accommodation_made_changes_details',
      'accommodation_making_changes_details',
      'accommodation_want_to_make_changes_details',
      'accommodation_needs_help_to_make_changes_details',
      'accommodation_thinking_about_making_changes_details',
      'accommodation_does_not_want_to_make_changes_details',
    ],
    next: 'accommodation-summary-analysis-temporary',
    template: 'forms/default',
    backLink: 'accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/no-accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'no_accommodation_reason',
      'no_accommodation_reason_other_details',
      'past_accommodation_details',
      'suitable_housing_planned',
      'future_accommodation_type',
      'suitable_housing_planned_awaiting_assessment_details',
      'awaiting_accommodation_placement_details',
      'suitable_housing_planned_other_details',
      'accommodation_changes',
      'accommodation_made_changes_details',
      'accommodation_making_changes_details',
      'accommodation_want_to_make_changes_details',
      'accommodation_needs_help_to_make_changes_details',
      'accommodation_thinking_about_making_changes_details',
      'accommodation_does_not_want_to_make_changes_details',
    ],
    next: 'accommodation-summary-analysis-no-accommodation',
    template: 'forms/default',
    backLink: 'accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/no-accommodation-2': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'accommodation_changes',
      'accommodation_made_changes_details',
      'accommodation_making_changes_details',
      'accommodation_want_to_make_changes_details',
      'accommodation_needs_help_to_make_changes_details',
      'accommodation_thinking_about_making_changes_details',
      'accommodation_does_not_want_to_make_changes_details',
    ],
    next: 'accommodation-summary-analysis-no-accommodation',
    template: 'forms/default',
    backLink: 'accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
      { fieldCode: 'accommodation_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  // '/add-living-with-child': {
  //   pageTitle: 'Child details',
  //   controller: AddChildController,
  //   fields: ['child_name', 'child_date_of_birth', 'child_age', 'relationship_to_child', 'child_gender'],
  //   template: 'forms/default',
  //   next: [
  //     { field: 'current_accommodation', value: 'SETTLED', next: 'settled-accommodation' },
  //     { field: 'current_accommodation', value: 'TEMPORARY', next: 'temporary-accommodation' },
  //     'accommodation',
  //   ],
  // },
  // '/edit-living-with-child': {
  //   pageTitle: 'Child details',
  //   controller: EditChildController,
  //   fields: ['child_name', 'child_date_of_birth', 'child_age', 'relationship_to_child', 'child_gender'],
  //   template: 'forms/default',
  //   next: [
  //     { field: 'current_accommodation', value: 'SETTLED', next: 'settled-accommodation' },
  //     { field: 'current_accommodation', value: 'TEMPORARY', next: 'temporary-accommodation' },
  //     'accommodation',
  //   ],
  // },
  // '/add-living-with-partner': {
  //   pageTitle: 'Partner details',
  //   controller: AddPartnerController,
  //   fields: ['partner_name', 'partner_age', 'partner_gender'],
  //   template: 'forms/default',
  //   next: [
  //     { field: 'current_accommodation', value: 'SETTLED', next: 'settled-accommodation' },
  //     { field: 'current_accommodation', value: 'TEMPORARY', next: 'temporary-accommodation' },
  //     'accommodation',
  //   ],
  // },
  // '/edit-living-with-partner': {
  //   pageTitle: 'Partner details',
  //   controller: EditPartnerController,
  //   fields: ['partner_name', 'partner_age', 'partner_gender'],
  //   template: 'forms/default',
  //   next: [
  //     { field: 'current_accommodation', value: 'SETTLED', next: 'settled-accommodation' },
  //     { field: 'current_accommodation', value: 'TEMPORARY', next: 'temporary-accommodation' },
  //     'accommodation',
  //   ],
  // },
  '/accommodation-summary-analysis-no-accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'practitioner_analysis_patterns_of_behaviour',
      'practitioner_analysis_patterns_of_behaviour_details',
      'practitioner_analysis_strengths_or_protective_factors',
      'practitioner_analysis_strengths_or_protective_factors_details',
      'practitioner_analysis_risk_of_serious_harm',
      'practitioner_analysis_risk_of_serious_harm_details',
      'practitioner_analysis_risk_of_reoffending',
      'practitioner_analysis_risk_of_reoffending_details',
      'practitioner_analysis_related_to_risk',
      'practitioner_analysis_related_to_risk_details',
    ],
    next: 'accommodation-analysis-complete-no-accommodation#practitioner-analysis',
    template: 'forms/sbna-poc/accommodation-summary-analysis-no-accommodation',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_analysis_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
    ],
  },
  '/accommodation-summary-analysis-temporary': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'practitioner_analysis_patterns_of_behaviour',
      'practitioner_analysis_patterns_of_behaviour_details',
      'practitioner_analysis_strengths_or_protective_factors',
      'practitioner_analysis_strengths_or_protective_factors_details',
      'practitioner_analysis_risk_of_serious_harm',
      'practitioner_analysis_risk_of_serious_harm_details',
      'practitioner_analysis_risk_of_reoffending',
      'practitioner_analysis_risk_of_reoffending_details',
      'practitioner_analysis_related_to_risk',
      'practitioner_analysis_related_to_risk_details',
    ],
    next: 'accommodation-analysis-complete-temporary#practitioner-analysis',
    template: 'forms/sbna-poc/accommodation-summary-analysis-temporary',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_analysis_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
    ],
  },
  '/accommodation-summary-analysis-settled': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: [
      'practitioner_analysis_patterns_of_behaviour',
      'practitioner_analysis_patterns_of_behaviour_details',
      'practitioner_analysis_strengths_or_protective_factors',
      'practitioner_analysis_strengths_or_protective_factors_details',
      'practitioner_analysis_risk_of_serious_harm',
      'practitioner_analysis_risk_of_serious_harm_details',
      'practitioner_analysis_risk_of_reoffending',
      'practitioner_analysis_risk_of_reoffending_details',
      'practitioner_analysis_related_to_risk',
      'practitioner_analysis_related_to_risk_details',
    ],
    next: 'accommodation-analysis-complete-settled#practitioner-analysis',
    template: 'forms/sbna-poc/accommodation-summary-analysis-settled',
    section: 'accommodation',
    sectionProgressRules: [
      {
        fieldCode: 'accommodation_analysis_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
    ],
  },
  '/accommodation-analysis-complete-settled': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    next: 'employment-education-finance',
    template: 'forms/sbna-poc/accommodation-analysis-complete-settled',
    section: 'accommodation',
  },
  '/accommodation-analysis-complete-temporary': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    next: 'employment-education-finance',
    template: 'forms/sbna-poc/accommodation-analysis-complete-temporary',
    section: 'accommodation',
  },
  '/accommodation-analysis-complete-no-accommodation': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    next: 'employment-education-finance',
    template: 'forms/sbna-poc/accommodation-analysis-complete-no-accommodation',
    section: 'accommodation',
  },
  '/employment-education-finance': {
    pageTitle: 'Employment and education ',
    controller: SaveAndContinueController,
    fields: [],
    template: 'forms/default',
    navigationOrder: 2,
    section: 'employment-education-finance',
  },
  '/drug-use': {
    pageTitle: 'Drug use',
    controller: SaveAndContinueController,
    fields: ['drug_use'],
    next: [
      { field: 'drug_use', value: 'YES', next: 'drug-use-type' },
      { field: 'drug_use', value: 'NO', next: 'no-drug-use-summary' },
    ],
    template: 'forms/default',
    navigationOrder: 4,
    section: 'drug-use',
    sectionProgressRules: [
      {
        fieldCode: 'drug_use_section_complete',
        conditionFn: (isValid: boolean, answers: Record<string, string | string[]>) =>
          isValid && answers.drug_use === 'NO' ? 'YES' : 'NO',
      },
      { fieldCode: 'drug_use_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/drug-use-type': {
    pageTitle: 'Drug use',
    controller: SaveAndContinueController,
    fields: ['drug_use_type', 'other_drug_details'],
    next: 'drug-usage-details',
    template: 'forms/default',
    backLink: 'drug-use',
    section: 'drug-use',
    sectionProgressRules: [
      { fieldCode: 'drug_use_section_complete', conditionFn: () => 'NO' },
      { fieldCode: 'drug_use_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/drug-usage-details': {
    pageTitle: 'Usage details',
    controller: SaveAndContinueController,
    fields: [
      'drug_usage_heroin',
      'past_drug_usage_heroin',
      'drug_usage_methadone_not_prescribed',
      'past_drug_usage_methadone_not_prescribed',
      'drug_usage_crack',
      'past_drug_usage_crack',
      'drug_usage_amphetamines',
      'past_drug_usage_amphetamines',
      'drug_usage_benzodiazepines',
      'past_drug_usage_benzodiazepines',
      'drug_usage_other_drug',
      'past_drug_usage_other',
      'drug_usage_cannabis',
      'past_drug_usage_cannabis',
      'drug_usage_cocaine',
      'past_drug_usage_cocaine',
      'drug_usage_ecstasy',
      'past_drug_usage_ecstasy',
      'drug_usage_ketamine',
      'past_drug_usage_ketamine',
      'drug_usage_methadone_prescribed',
      'past_drug_usage_methadone_prescribed',
      'drug_usage_non_prescribed_medication',
      'past_drug_usage_non_prescribed_medication',
      'drug_usage_psychoactive_substances',
      'past_drug_usage_psychoactive_substances',
      'daily_injecting_drug_heroin',
      'weekly_injecting_drug_heroin',
      'monthly_injecting_drug_heroin',
      'occasionally_injecting_drug_heroin',
      'daily_drug_usage_treatment_heroin',
      'weekly_drug_usage_treatment_heroin',
      'monthly_drug_usage_treatment_heroin',
      'occasionally_drug_usage_treatment',
      'past_injecting_drug_heroin',
      'daily_injecting_drug_methadone_not_prescribed',
      'weekly_injecting_methadone_not_prescribed',
      'monthly_injecting_drug_methadone_not_prescribed',
      'occasionally_injecting_drug_methadone_not_prescribed',
      'past_injecting_drug_methadone_not_prescribed',
      'daily_injecting_drug_crack',
      'weekly_injecting_drug_crack',
      'monthly_injecting_drug_crack',
      'occasionally_injecting_drug_crack',
      'past_injecting_drug_crack',
      'daily_injecting_drug_amphetamines',
      'weekly_injecting_drug_amphetamines',
      'monthly_injecting_drug_amphetamines',
      'occasionally_injecting_drug_amphetamines',
      'past_injecting_drug_amphetamines',
      'daily_injecting_drug_benzodiazepines',
      'weekly_injecting_drug_benzodiazepines',
      'monthly_injecting_drug_benzodiazepines',
      'occasionally_injecting_drug_benzodiazepines',
      'past_injecting_drug_benzodiazepines',
      'daily_injecting_drug_other_drug',
      'weekly_injecting_drug_other_drug',
      'monthly_injecting_drug_other_drug',
      'occasionally_injecting_drug_other_drug',
      'past_injecting_drug_other',
    ],
    next: 'drug-use-details',
    template: 'forms/sbna-poc/drug-usage',
    backLink: 'drug-use-type',
    section: 'drug-use',
    sectionProgressRules: [
      { fieldCode: 'drug_use_section_complete', conditionFn: () => 'NO' },
      { fieldCode: 'drug_use_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/drug-use-details': {
    pageTitle: 'Drug use',
    controller: SaveAndContinueController,
    fields: [
      'drug_use_reasons',
      'drug_use_reasons_details',
      'drug_use_impact',
      'drug_use_impact_details',
      'reducing_or_stopping_drug_use',
      'reducing_or_stopping_drug_use_details',
      'motivated_stopping_drug_use',
      'drug_use_changes',
    ],
    // next: ,
    template: 'forms/default',
    backLink: 'drug-usage-details',
    section: 'drug-use',
    sectionProgressRules: [
      { fieldCode: 'drug_use_section_complete', conditionFn: () => 'YES' },
      { fieldCode: 'drug_use_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/no-drug-use-summary': {
    pageTitle: 'Drug use',
    controller: SaveAndContinueController,
    fields: [
      'patterns_or_behaviours',
      'patterns_or_behaviours_yes_details',
      'patterns_or_behaviours_no_details',
      'strengths_or_protective_factors',
      'strengths_or_protective_factors_yes_details',
      'strengths_or_protective_factors_no_details',
      'linked_to_risk_of_serious_harm',
      'linked_to_risk_of_serious_harm_yes_details',
      'linked_to_risk_of_serious_harm_no_details',
      'linked_to_risk_of_reoffending',
      'linked_to_risk_of_reoffending_yes_details',
      'linked_to_risk_of_reoffending_no_details',
      'not_related_to_risk',
      'not_related_to_risk_yes_details',
      'not_related_to_risk_no_details',
    ],
    next: 'no-drug-use-analysis-complete',
    template: 'forms/sbna-poc/no-drug-use-summary-analysis',
    section: 'drug-use',
    sectionProgressRules: [{ fieldCode: 'drug_use_analysis_section_complete', conditionFn: () => 'YES' }],
  },
  '/no-drug-use-analysis-complete': {
    pageTitle: 'Drug use',
    controller: SaveAndContinueController,
    fields: [],
    template: 'forms/sbna-poc/no-drug-use-analysis-complete',
    section: 'drug-use',
  },
  '/finance': {
    pageTitle: 'Finance',
    controller: SaveAndContinueController,
    fields: [
      'finance_income',
      'finance_bank_account',
      'finance_money_management',
      'finance_gambling',
      'finance_debt',
      'changes_to_finance',
      'finance_no_change_details',
      'finance_thinking_change_details',
      'finance_help_change_details',
      'finance_known_change_details',
      'finance_active_change_details,',
      'finance_positive_change_details',
      'unknown_debt_details',
      'yes__someone_elses_formal_debt_to_others_details',
      'yes_someone_elses_debt_to_others_details',
      'yes_someone_elses_formal_debt_details',
      'yes_someone_elses_type_of_debt',
      'yes_formal_debt_to_others_details',
      'yes_debt_to_others_details',
      'yes_formal_debt_details',
      'yes_type_of_debt',
      'unknown_gambling_details',
      'no_gambling_details',
      'yes_someone_elses_gambling_details',
      'yes_their_gambling_details',
      'bad_money_management_details',
      'fairly_bad_money_management_details',
      'fairly_good_money_management_details',
      'good_money_management_details',
      'other_income_details',
      'family_or_friends_details',
    ],
    navigationOrder: 3,
    next: 'finance-summary-analysis',
    template: 'forms/default',
    section: 'finance',
    sectionProgressRules: [
      {
        fieldCode: 'finance_section_complete',
        conditionFn: (isValidated: boolean) => (isValidated ? 'YES' : 'NO'),
      },
      { fieldCode: 'finance_analysis_section_complete', conditionFn: () => 'NO' },
    ],
  },
  '/finance-summary-analysis': {
    pageTitle: 'Finance',
    controller: SaveAndContinueController,
    fields: [
      'finance_practitioner_analysis_patterns_of_behaviour',
      'finance_practitioner_analysis_patterns_of_behaviour_details',
      'finance_practitioner_analysis_strengths_or_protective_factors',
      'finance_practitioner_analysis_strengths_or_protective_factors_details',
      'finance_practitioner_analysis_risk_of_serious_harm',
      'finance_practitioner_analysis_risk_of_serious_harm_details',
      'finance_practitioner_analysis_risk_of_reoffending',
      'finance_practitioner_analysis_risk_of_reoffending_details',
      'finance_practitioner_analysis_related_to_risk',
      'finance_practitioner_analysis_related_to_risk_details',
    ],
    next: 'drug-use',
    template: 'forms/sbna-poc/finance-summary-analysis',
    section: 'finance',
    sectionProgressRules: [{ fieldCode: 'finance_analysis_section_complete', conditionFn: () => 'YES' }],
  },
}

const addStep = (options: FormWizard.Step & { path: string }, steps: FormWizard.Steps): FormWizard.Steps => ({
  ...steps,
  [options.path]: {
    ...options,
    pageTitle: options.pageTitle,
    controller: options.controller || SaveAndContinueController,
    fields: options.fields || [],
    template: options.template || 'forms/default',
    backLink: options.backLink || null, // override FormWizard behaviour to provide a generated backlink, these will be set manually in config
  },
})

const steps: FormWizard.Steps = Object.entries(stepOptions).reduce(
  (allSteps: FormWizard.Steps, [path, step]: [string, FormWizard.Step]) => addStep({ path, ...step }, allSteps),
  {},
)

export default steps
