import FormWizard from 'hmpo-form-wizard'
import SaveAndContinueController from './controllers/saveAndContinueController'
import StartController from './controllers/startController'

const steps: FormWizard.Steps = {
  '/start': {
    pageTitle: 'POC Form',
    controller: StartController,
    reset: true,
    entryPoint: true,
    template: `forms/sbna-poc/start`,
    next: 'accommodation',
  },
  '/accommodation': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['current_accommodation'],
    next: [
      { field: 'current_accommodation', value: 'SETTLED', next: 'settled-accommodation' },
      { field: 'current_accommodation', value: 'TEMPORARY', next: 'temporary-accommodation' },
      { field: 'current_accommodation', value: 'NO_ACCOMMODATION', next: 'no-accommodation' },
    ],
    template: 'forms/default',
    navigationOrder: 1,
  },
  '/settled-accommodation': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['living_with'],
    next: 'settled-accommodation-2',
    template: 'forms/default',
  },
  '/settled-accommodation-2': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['suitable_housing_location'],
    next: 'settled-accommodation-3',
    template: 'forms/default',
  },
  '/settled-accommodation-3': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['suitable_housing'],
    next: 'settled-accommodation-4',
    template: 'forms/default',
  },
  '/settled-accommodation-4': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['accommodation_changes'],
    next: 'settled-accommodation-5',
    template: 'forms/default',
  },
  '/settled-accommodation-5': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['accommodation_changes_details'],
    next: 'settled-accommodation-summary',
    template: 'forms/default',
  },
  '/temporary-accommodation': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['living_with'],
    next: 'temporary-accommodation-2',
    template: 'forms/default',
  },
  '/temporary-accommodation-2': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['suitable_housing_location'],
    next: 'temporary-accommodation-3',
    template: 'forms/default',
  },
  '/temporary-accommodation-3': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['suitable_housing'],
    next: 'temporary-accommodation-4',
    template: 'forms/default',
  },
  '/temporary-accommodation-4': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['accommodation_changes'],
    next: 'temporary-accommodation-5',
    template: 'forms/default',
  },
  '/temporary-accommodation-5': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['accommodation_changes_details'],
    next: 'temporary-accommodation-summary',
    template: 'forms/default',
  },
  '/temporary-accommodation-summary': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    next: 'employment-education-finance',
    template: 'forms/sbna-poc/summary',
  },
  '/no-accommodation': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['no_accommodation_details'],
    next: 'no-accommodation-2',
    template: 'forms/default',
  },
  '/no-accommodation-2': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['suitable_housing_details'],
    next: 'no-accommodation-3',
    template: 'forms/default',
  },
  '/no-accommodation-3': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['suitable_housing_planned'],
    next: 'no-accommodation-4',
    template: 'forms/default',
  },
  '/no-accommodation-4': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['accommodation_changes'],
    next: 'no-accommodation-5',
    template: 'forms/default',
  },
  '/no-accommodation-5': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    fields: ['accommodation_changes_details'],
    next: 'no-accommodation-summary',
    template: 'forms/default',
  },
  '/no-accommodation-summary': {
    pageTitle: 'Housing',
    controller: SaveAndContinueController,
    next: 'employment-education-finance',
    template: 'forms/sbna-poc/summary',
  },
  '/employment-education-finance': {
    pageTitle: 'Employment, education and finance',
    controller: SaveAndContinueController,
    fields: [],
    template: 'forms/default',
    navigationOrder: 2,
  },
  '/accommodation-summary-analysis': {
    pageTitle: 'Accommodation',
    controller: SaveAndContinueController,
    fields: ['accommodation_practitioner_analysis', 'accommodation_serious_harm', 'accommodation_risk_of_reoffending'],
    next: 'employment-education-finance',
    template: 'forms/sbna-poc/accommodation-summary-analysis',
  },
}

export default steps
