export default (summaryPage: string, analysisCompletePage: string, positionNumber: number) => {
  const questionWith = sectionName => `Is Sam’s ${sectionName} linked to risk of serious harm?`
  const summaryQuestion = 'Linked to risk of serious harm'

  describe(questionWith('{SECTION_NAME}'), () => {
    const options = ['Yes', 'No']

    it(`displays and validates the question`, () => {
      cy.getSectionName()
        .then(sectionName => cy.getQuestion(questionWith(sectionName)))
        .isQuestionNumber(positionNumber)
        .hasHint(null)
        .hasRadios(options)
        .getNextQuestion()
        .hasTitle('Give details')
        .hasLimit(1000)
        .hasHint(null)
      cy.markAsComplete()
      cy.assertStepUrlIs(summaryPage)
      cy.getSectionName()
        .then(sectionName => cy.getQuestion(questionWith(sectionName)))
        .hasValidationError('Select if linked to risk of serious harm')
      cy.checkAccessibility()
    })

    it('"Give details" is optional when selecting "No"', () => {
      cy.getSectionName()
        .then(sectionName => cy.getQuestion(questionWith(sectionName)))
        .getRadio('No')
        .clickLabel()
      cy.markAsComplete()
      cy.getSectionName()
        .then(sectionName => cy.getQuestion(questionWith(sectionName)))
        .hasNoValidationError()
        .getNextQuestion()
        .hasTitle('Give details')
        .hasNoValidationError()
      cy.visitStep(analysisCompletePage)
      cy.get('#tab_practitioner-analysis').click()
      cy.getAnalysisSummary(summaryQuestion).getAnalysisAnswer('No').hasNoSecondaryAnswer()
      cy.checkAccessibility()
      cy.getAnalysisSummary(summaryQuestion).clickChangeAnalysis()
      cy.assertStepUrlIs(summaryPage)
      cy.getSectionName().then(sectionName => cy.getQuestion(questionWith(sectionName)))
    })

    it('"Give details" is required when selecting "Yes"', () => {
      cy.getSectionName()
        .then(sectionName => cy.getQuestion(questionWith(sectionName)))
        .getRadio('Yes')
        .clickLabel()
      cy.markAsComplete()
      cy.getSectionName()
        .then(sectionName => cy.getQuestion(questionWith(sectionName)))
        .hasNoValidationError()
        .getNextQuestion()
        .hasTitle('Give details')
        .hasValidationError('Enter details')
        .enterText('some details')
      cy.checkAccessibility()
      cy.markAsComplete()
      cy.getSectionName()
        .then(sectionName => cy.getQuestion(questionWith(sectionName)))
        .hasNoValidationError()
        .getNextQuestion()
        .hasTitle('Give details')
        .hasNoValidationError()
      cy.visitStep(analysisCompletePage)
      cy.get('#tab_practitioner-analysis').click()
      cy.getAnalysisSummary(summaryQuestion).getAnalysisAnswer('Yes').hasSecondaryAnalysisAnswer('some details')
      cy.checkAccessibility()
      cy.getAnalysisSummary(summaryQuestion).clickChangeAnalysis()
      cy.assertStepUrlIs(summaryPage)
      cy.getSectionName().then(sectionName => cy.getQuestion(questionWith(sectionName)))
    })
  })
}
