---
# Per environment values which override defaults in hmpps-strengths-based-needs-assessments-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    hosts:
      - strengths-based-needs-preprod.hmpps.service.justice.gov.uk
      - strengths-based-needs-assessments-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://strengths-based-needs-assessments-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    SBNA_API_URL: "http://hmpps-strengths-based-needs-assessments-api.hmpps-strengths-based-needs-assessments-preprod.svc.cluster.local"
    HMPPS_ARNS_HANDOVER_URL: "https://arns-handover-service-preprod.hmpps.service.justice.gov.uk"
    OASYS_URL: "https://pp.oasys.service.justice.gov.uk"

  namespace_secrets:
    hmpps-strengths-based-needs-assessments-ui-feedback-url:
      FEEDBACK_URL: "FEEDBACK_URL"

generic-prometheus-alerts:
  alertSeverity: hmpps-strengths-based-needs-assessments
