---
# Per environment values which override defaults in hmpps-strengths-based-needs-assessments-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    hosts: 
      - strengths-based-needs-dev.hmpps.service.justice.gov.uk
      - strengths-based-needs-assessments-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://strengths-based-needs-assessments-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SBNA_API_URL: "http://hmpps-strengths-based-needs-assessments-api.hmpps-strengths-based-needs-assessments-dev.svc.cluster.local"
    HMPPS_ARNS_HANDOVER_URL: "https://arns-handover-service-dev.hmpps.service.justice.gov.uk"
    OASYS_URL: "https://arns-oastub-dev.hmpps.service.justice.gov.uk/"

  allowlist:
    capita-dev: 51.104.16.30/31
    captia-further: 172.167.141.40/32
    neil-test: 51.155.102.238/32
    capita-developers-vms-one: 85.115.52.180/32
    capita-developers-vms-two: 85.115.52.200/29
    capita-developers-vms-three: 85.115.53.180/32
    capita-developers-vms-four: 85.115.53.200/29
    capita-developers-vms-five: 85.115.54.180/32
    capita-developers-vms-six: 85.115.54.200/29
    joel-app-sec-1: 100.64.10.206/32
    joel-app-sec-2: 86.134.133.78/32

generic-prometheus-alerts:
  alertSeverity: hmpps-strengths-based-needs-assessments
