name: Save end-to-end test timings

on:
  workflow_call:
    inputs:
      timings:
        description: "Map with container numbers to timings JSON"
        required: true
        type: string

permissions:
  contents: read

jobs:
  merge-timings:
    runs-on: ubuntu-latest
    outputs:
      durations: ${{ steps.merge-timings.outputs.durations }}
    steps:
      - name: Merge container timings
        id: merge-timings
        run: |
          echo "durations=$(echo ${{ inputs.timings }} | jq 'map(.durations) | add | map(.id = (.spec | gsub("[^a-zA-Z0-9]+"; "-") | rtrimstr("-")))')" >> $GITHUB_OUTPUT

  save-timings-cache:
    runs-on: ubuntu-latest
    needs: merge-timings
    strategy:
      matrix:
        duration: ${{ fromJSON(needs.merge-timings.outputs.durations) }}
    steps:
      - uses: actions/checkout@v4
      - name: Create timing file
        run: |
          mkdir -p timings
          echo ${{ matrix.duration }} | jq 'del(.id)' > timings/${{ matrix.duration.id }}.json
      - name: Save timing cache
        uses: actions/cache@v4
        with:
          path: timings/${{ matrix.duration.id }}.json
          key: ${{ hashFiles(matrix.duration.path) }}
