name: Run end-to-end tests

on:
  workflow_call:
    inputs:
      app_version:
        description: App version
        required: true
        type: string

jobs:
  get-timings:
    uses: ./.github/workflows/cypress_get_timings.yml
    with:
      spec-file-patterns: cypress/e2e/**/*.cy.ts

  e2e-test:
    runs-on: ubuntu-latest
    needs: get-timings
    env:
      APP_VERSION: ${{ inputs.app_version }}
    strategy:
      fail-fast: false
      matrix:
        container: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    outputs:
      timings-1: ${{ steps.timings.outputs.t1 }}
      timings-2: ${{ steps.timings.outputs.t2 }}
      timings-3: ${{ steps.timings.outputs.t3 }}
      timings-4: ${{ steps.timings.outputs.t4 }}
      timings-5: ${{ steps.timings.outputs.t5 }}
      timings-6: ${{ steps.timings.outputs.t6 }}
      timings-7: ${{ steps.timings.outputs.t7 }}
      timings-8: ${{ steps.timings.outputs.t8 }}
      timings-9: ${{ steps.timings.outputs.t9 }}
      timings-10: ${{ steps.timings.outputs.t10 }}
    steps:
      - uses: actions/checkout@v4

      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: build_image
          path: ${{ runner.temp }}

      - name: Load image
        run: docker load --input ${{ runner.temp }}/build_image.tar

      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        env:
          cache-name: node-modules
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - uses: ./.github/actions/cypress_create_timings_file

      - name: Stand up a test environment
        run: make up

      - name: Run the end-to-end tests
        uses: cypress-io/github-action@v6
        with:
          publish-summary: false
          browser: edge
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          SPLIT_FILE: 'timings.json'
          SPLIT_OUTPUT_FILE: 'timings-out.json'

      - uses: ./.github/actions/cypress_output_updated_timings

      - name: Export container logs
        if: failure()
        run: make save-logs OUTPUT_LOGS_DIR=${{ runner.temp }}/docker-logs

      - name: Upload test results
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: e2e_test_results
          path: |
            test_results
            cypress/videos
            cypress/screenshots
            ${{ runner.temp }}/docker-logs

  save-timings:
    uses: ./.github/workflows/cypress_save_timings.yml
    needs: e2e-test
    if: '!cancelled()'
    with:
      timings: ${{ needs.e2e-test.outputs }}
