name: Run end-to-end tests

on:
  workflow_call:
    inputs:
      app_version:
        description: App version
        required: true
        type: string
      timings:
        description: "Contents of timings.json"
        required: true
        type: string
    outputs:
      timings:
        description: "Contents of updated timings.json"
        value: ${{ jobs.e2e_test.outputs }}

permissions:
  contents: read

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${{ inputs.app_version }}
    strategy:
      fail-fast: false
      matrix:
        container: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    outputs:
      timings-${{ matrix.container }}: ${{ steps.updated-timings.outputs.timings }}
    steps:
      - uses: actions/checkout@v4

      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: build_image
          path: ${{ runner.temp }}

      - name: Load image
        run: docker load --input ${{ runner.temp }}/build_image.tar

      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        env:
          cache-name: node-modules
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Create timings.json
        if: ${{ inputs.timings != '' }}
        run: echo ${{ input.timings }} > timings.json

      - name: Stand up a test environment
        run: make up

      - name: Run the end-to-end tests
        uses: cypress-io/github-action@v6
        with:
          publish-summary: false
          browser: edge
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          SPLIT_FILE: 'timings.json'

      - name: Create updated timing files
        id: updated-timings
        if: '!cancelled()'
        run: echo "timings=$(cat timings.json)" >> $GITHUB_OUTPUT

      - name: Export container logs
        if: failure()
        run: make save-logs OUTPUT_LOGS_DIR=${{ runner.temp }}/docker-logs

      - name: Upload test results
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: e2e_test_results
          path: |
            test_results
            cypress/videos
            cypress/screenshots
            ${{ runner.temp }}/docker-logs
