name: Save end-to-end test timings

on:
  workflow_call:
    inputs:
      timings:
        description: "Map with container numbers to timings JSON"
        required: true
        type: string

permissions:
  contents: read

jobs:
  merge-timings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge container timings
        id: merge-container-timings
        run: |
          echo ${{ inputs.timings }} \
            | jq -r 'map(.durations) | add | map({spec, duration, hash: .spec})' \
            | jq -c '.[]' \
            | while read -r line; \
              do spec=$(echo "$line" | jq -r '.spec'); \
              hash=$(md5sum "$spec" 2>/dev/null | cut -d " " -f1 || echo "MISSING_FILE"); \
              echo "$line" | jq --arg hash "$hash" '. + {hash: $hash}'; \
            done \
            | jq -s '{durations: .}' > merged-container-timings.json
          echo "timings=$(cat merged-container-timings.json)" >> $GITHUB_OUTPUT
      - name: Restore timings cache
        uses: actions/cache/restore@v4
        with:
          path: timings-cache.json
          key: timings-cache.json
      - name: Get cached timings
        id: get-cached-timings
        run: echo "timings=$(cat timings-cache.json)" >> $GITHUB_OUTPUT
      - name: Update timings cache
        id: update-timings-cache
        uses: ./.github/actions/update-timings-cache
        with:
          container-timings: ${{ steps.merge-container-timings.outputs.timings }}
          cached-timings: ${{ steps.get-cached-timings.outputs.timings }}
      - name: Create timings file to cache
        run: echo ${{ steps.update-timings-cache.outputs.timings }} > timings-cache.json
      - name: Delete Previous Cache
        continue-on-error: true
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "timings-cache.json" --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache timings
        uses: actions/cache/save@v4
        with:
          path: timings-cache.json
          key: timings-cache.json
