name: Save end-to-end test timings

on:
  workflow_call:

permissions:
  contents: read

jobs:
  get-spec-files:
    runs-on: ubuntu-latest
    outputs:
      spec-files: ${{ steps.find-spec-files.outputs.spec-files }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: timings-*
          merge-multiple: true
      - name: Find spec files
        id: find-spec-files
        run: find timings -type f -name "*.json" | jq -R -s -c 'split("\n")[:-1] | map(sub("^timings/"; "") | sub(".json$"; ""))' >> $GITHUB_OUTPUT
      - run: echo "${{ steps.find-spec-files.outputs.spec-files }}"

  save-timings-cache:
    runs-on: ubuntu-latest
    needs: get-spec-files
    strategy:
      matrix:
        spec-file: ${{ fromJSON(needs.get-spec-files.outputs.spec-files) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: timings-*
          merge-multiple: true
      - name: Save timing cache
        uses: actions/cache@v4
        with:
          path: timings/${{ matrix.spec-file }}.json
          key: ${{ hashFiles(matrix.spec-file) }}
