name: Build and test PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node_build:
    name: Build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_build.yml@v2
    secrets: inherit

  node_unit_tests:
    name: Unit tests
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_unit_tests.yml@v2
    needs: node_build
    secrets: inherit

  helm_lint:
    name: Helm lint
    strategy:
      matrix:
        environments: ['dev', 'test', 'preprod', 'prod']
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}

  build_docker:
    name: Build docker image
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      tag_latest: false
      push: false
      load: true
      docker_multiplatform: false
      upload_image_artifact: true
      image_artifact_retention_days: 2

  api_integration_tests:
    needs: build_docker
    uses: ./.github/workflows/api_integration_tests.yml
    with:
      app_version: ${{ needs.build_docker.outputs.app_version }}

  e2e_timings_get:
    uses: ./.github/workflows/e2e_timings_get.yml
    with:
      spec-file-patterns: cypress/e2e/**/*.cy.ts

  e2e_test:
    needs:
      - build_docker
      - e2e_timings_get
    uses: ./.github/workflows/e2e_test.yml
    with:
      app_version: ${{ needs.build_docker.outputs.app_version }}
      timings: ${{ needs.e2e_timings_get.outputs.timings }}

  e2e_timings_save:
    uses: ./.github/workflows/e2e_timings_save.yml
    needs: e2e_test
    if: '!cancelled()'
    with:
      timings: ${{ needs.e2e_test.outputs.timings }}
